// Code generated by ent, DO NOT EDIT.

package oauthloginstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldUpdatedAt, v))
}

// StateHash applies equality check predicate on the "state_hash" field. It's identical to StateHashEQ.
func StateHash(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldStateHash, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldProvider, v))
}

// RedirectURL applies equality check predicate on the "redirect_url" field. It's identical to RedirectURLEQ.
func RedirectURL(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldRedirectURL, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldUpdatedAt, v))
}

// StateHashEQ applies the EQ predicate on the "state_hash" field.
func StateHashEQ(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldStateHash, v))
}

// StateHashNEQ applies the NEQ predicate on the "state_hash" field.
func StateHashNEQ(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldStateHash, v))
}

// StateHashIn applies the In predicate on the "state_hash" field.
func StateHashIn(vs ...string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldStateHash, vs...))
}

// StateHashNotIn applies the NotIn predicate on the "state_hash" field.
func StateHashNotIn(vs ...string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldStateHash, vs...))
}

// StateHashGT applies the GT predicate on the "state_hash" field.
func StateHashGT(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldStateHash, v))
}

// StateHashGTE applies the GTE predicate on the "state_hash" field.
func StateHashGTE(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldStateHash, v))
}

// StateHashLT applies the LT predicate on the "state_hash" field.
func StateHashLT(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldStateHash, v))
}

// StateHashLTE applies the LTE predicate on the "state_hash" field.
func StateHashLTE(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldStateHash, v))
}

// StateHashContains applies the Contains predicate on the "state_hash" field.
func StateHashContains(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldContains(FieldStateHash, v))
}

// StateHashHasPrefix applies the HasPrefix predicate on the "state_hash" field.
func StateHashHasPrefix(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldHasPrefix(FieldStateHash, v))
}

// StateHashHasSuffix applies the HasSuffix predicate on the "state_hash" field.
func StateHashHasSuffix(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldHasSuffix(FieldStateHash, v))
}

// StateHashEqualFold applies the EqualFold predicate on the "state_hash" field.
func StateHashEqualFold(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEqualFold(FieldStateHash, v))
}

// StateHashContainsFold applies the ContainsFold predicate on the "state_hash" field.
func StateHashContainsFold(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldContainsFold(FieldStateHash, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldContainsFold(FieldProvider, v))
}

// RedirectURLEQ applies the EQ predicate on the "redirect_url" field.
func RedirectURLEQ(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldRedirectURL, v))
}

// RedirectURLNEQ applies the NEQ predicate on the "redirect_url" field.
func RedirectURLNEQ(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldRedirectURL, v))
}

// RedirectURLIn applies the In predicate on the "redirect_url" field.
func RedirectURLIn(vs ...string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldRedirectURL, vs...))
}

// RedirectURLNotIn applies the NotIn predicate on the "redirect_url" field.
func RedirectURLNotIn(vs ...string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldRedirectURL, vs...))
}

// RedirectURLGT applies the GT predicate on the "redirect_url" field.
func RedirectURLGT(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldRedirectURL, v))
}

// RedirectURLGTE applies the GTE predicate on the "redirect_url" field.
func RedirectURLGTE(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldRedirectURL, v))
}

// RedirectURLLT applies the LT predicate on the "redirect_url" field.
func RedirectURLLT(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldRedirectURL, v))
}

// RedirectURLLTE applies the LTE predicate on the "redirect_url" field.
func RedirectURLLTE(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldRedirectURL, v))
}

// RedirectURLContains applies the Contains predicate on the "redirect_url" field.
func RedirectURLContains(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldContains(FieldRedirectURL, v))
}

// RedirectURLHasPrefix applies the HasPrefix predicate on the "redirect_url" field.
func RedirectURLHasPrefix(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldHasPrefix(FieldRedirectURL, v))
}

// RedirectURLHasSuffix applies the HasSuffix predicate on the "redirect_url" field.
func RedirectURLHasSuffix(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldHasSuffix(FieldRedirectURL, v))
}

// RedirectURLEqualFold applies the EqualFold predicate on the "redirect_url" field.
func RedirectURLEqualFold(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEqualFold(FieldRedirectURL, v))
}

// RedirectURLContainsFold applies the ContainsFold predicate on the "redirect_url" field.
func RedirectURLContainsFold(v string) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldContainsFold(FieldRedirectURL, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.FieldNotNull(FieldConsumedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthLoginState) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthLoginState) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthLoginState) predicate.OAuthLoginState {
	return predicate.OAuthLoginState(sql.NotPredicates(p))
}
