// Code generated by ent, DO NOT EDIT.

package conversationmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the conversationmember type in the database.
	Label = "conversation_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldBizID holds the string denoting the biz_id field in the database.
	FieldBizID = "biz_id"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldMemberType holds the string denoting the member_type field in the database.
	FieldMemberType = "member_type"
	// FieldMemberID holds the string denoting the member_id field in the database.
	FieldMemberID = "member_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldReadSeq holds the string denoting the read_seq field in the database.
	FieldReadSeq = "read_seq"
	// FieldLastReadAt holds the string denoting the last_read_at field in the database.
	FieldLastReadAt = "last_read_at"
	// FieldIsMuted holds the string denoting the is_muted field in the database.
	FieldIsMuted = "is_muted"
	// FieldIsPinned holds the string denoting the is_pinned field in the database.
	FieldIsPinned = "is_pinned"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// Table holds the table name of the conversationmember in the database.
	Table = "conversation_members"
)

// Columns holds all SQL columns for conversationmember fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldBizID,
	FieldConversationID,
	FieldMemberType,
	FieldMemberID,
	FieldRole,
	FieldReadSeq,
	FieldLastReadAt,
	FieldIsMuted,
	FieldIsPinned,
	FieldStatus,
	FieldJoinedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMemberType holds the default value on creation for the "member_type" field.
	DefaultMemberType int8
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole int8
	// DefaultReadSeq holds the default value on creation for the "read_seq" field.
	DefaultReadSeq int64
	// DefaultIsMuted holds the default value on creation for the "is_muted" field.
	DefaultIsMuted bool
	// DefaultIsPinned holds the default value on creation for the "is_pinned" field.
	DefaultIsPinned bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultJoinedAt holds the default value on creation for the "joined_at" field.
	DefaultJoinedAt func() time.Time
)

// OrderOption defines the ordering options for the ConversationMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBizID orders the results by the biz_id field.
func ByBizID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBizID, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByMemberType orders the results by the member_type field.
func ByMemberType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberType, opts...).ToFunc()
}

// ByMemberID orders the results by the member_id field.
func ByMemberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByReadSeq orders the results by the read_seq field.
func ByReadSeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadSeq, opts...).ToFunc()
}

// ByLastReadAt orders the results by the last_read_at field.
func ByLastReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReadAt, opts...).ToFunc()
}

// ByIsMuted orders the results by the is_muted field.
func ByIsMuted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsMuted, opts...).ToFunc()
}

// ByIsPinned orders the results by the is_pinned field.
func ByIsPinned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPinned, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}
