// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppSettingsColumns holds the columns for the "app_settings" table.
	AppSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Default: ""},
	}
	// AppSettingsTable holds the schema information for the "app_settings" table.
	AppSettingsTable = &schema.Table{
		Name:       "app_settings",
		Columns:    AppSettingsColumns,
		PrimaryKey: []*schema.Column{AppSettingsColumns[0]},
	}
	// AuthActionTokensColumns holds the columns for the "auth_action_tokens" table.
	AuthActionTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "token_id", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "user_biz_id", Type: field.TypeInt64},
		{Name: "purpose", Type: field.TypeString, Size: 32},
		{Name: "token_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "target_email_normalized", Type: field.TypeString, Size: 320, Default: ""},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "consumed_at", Type: field.TypeTime, Nullable: true},
	}
	// AuthActionTokensTable holds the schema information for the "auth_action_tokens" table.
	AuthActionTokensTable = &schema.Table{
		Name:       "auth_action_tokens",
		Columns:    AuthActionTokensColumns,
		PrimaryKey: []*schema.Column{AuthActionTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authactiontoken_user_biz_id_purpose_consumed_at_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AuthActionTokensColumns[4], AuthActionTokensColumns[5], AuthActionTokensColumns[9], AuthActionTokensColumns[8]},
			},
			{
				Name:    "authactiontoken_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AuthActionTokensColumns[8]},
			},
		},
	}
	// AuthRefreshTokensColumns holds the columns for the "auth_refresh_tokens" table.
	AuthRefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "token_id", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "user_biz_id", Type: field.TypeInt64},
		{Name: "token_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "replaced_by_token_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoke_reason", Type: field.TypeString, Size: 64, Default: ""},
	}
	// AuthRefreshTokensTable holds the schema information for the "auth_refresh_tokens" table.
	AuthRefreshTokensTable = &schema.Table{
		Name:       "auth_refresh_tokens",
		Columns:    AuthRefreshTokensColumns,
		PrimaryKey: []*schema.Column{AuthRefreshTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authrefreshtoken_user_biz_id_revoked_at_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AuthRefreshTokensColumns[4], AuthRefreshTokensColumns[8], AuthRefreshTokensColumns[7]},
			},
			{
				Name:    "authrefreshtoken_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AuthRefreshTokensColumns[7]},
			},
		},
	}
	// OauthLoginStatesColumns holds the columns for the "oauth_login_states" table.
	OauthLoginStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "state_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "provider", Type: field.TypeString, Size: 32},
		{Name: "redirect_url", Type: field.TypeString, Size: 1024},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "consumed_at", Type: field.TypeTime, Nullable: true},
	}
	// OauthLoginStatesTable holds the schema information for the "oauth_login_states" table.
	OauthLoginStatesTable = &schema.Table{
		Name:       "oauth_login_states",
		Columns:    OauthLoginStatesColumns,
		PrimaryKey: []*schema.Column{OauthLoginStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthloginstate_provider_consumed_at_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthLoginStatesColumns[4], OauthLoginStatesColumns[7], OauthLoginStatesColumns[6]},
			},
		},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "biz_id", Type: field.TypeInt64, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "version", Type: field.TypeInt, Default: 1},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "biz_id", Type: field.TypeInt64, Unique: true},
		{Name: "email", Type: field.TypeString, Size: 320},
		{Name: "email_normalized", Type: field.TypeString, Unique: true, Size: 320},
		{Name: "email_verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "password_hash_alg", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "password_set_at", Type: field.TypeTime, Nullable: true},
		{Name: "display_name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "avatar_url", Type: field.TypeString, Size: 1024, Default: ""},
		{Name: "status", Type: field.TypeString, Size: 32, Default: "active"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[12], UsersColumns[1]},
			},
			{
				Name:    "user_email_verified_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6]},
			},
		},
	}
	// UserIdentitiesColumns holds the columns for the "user_identities" table.
	UserIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "biz_id", Type: field.TypeInt64, Unique: true},
		{Name: "user_biz_id", Type: field.TypeInt64},
		{Name: "provider", Type: field.TypeString, Size: 32},
		{Name: "provider_user_id", Type: field.TypeString, Size: 255},
		{Name: "provider_email", Type: field.TypeString, Size: 320, Default: ""},
		{Name: "provider_email_normalized", Type: field.TypeString, Size: 320, Default: ""},
		{Name: "provider_email_verified", Type: field.TypeBool, Default: false},
		{Name: "display_name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "avatar_url", Type: field.TypeString, Size: 1024, Default: ""},
		{Name: "profile_url", Type: field.TypeString, Size: 1024, Default: ""},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UserIdentitiesTable holds the schema information for the "user_identities" table.
	UserIdentitiesTable = &schema.Table{
		Name:       "user_identities",
		Columns:    UserIdentitiesColumns,
		PrimaryKey: []*schema.Column{UserIdentitiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "useridentity_provider_provider_user_id",
				Unique:  true,
				Columns: []*schema.Column{UserIdentitiesColumns[5], UserIdentitiesColumns[6]},
			},
			{
				Name:    "useridentity_user_biz_id_provider",
				Unique:  true,
				Columns: []*schema.Column{UserIdentitiesColumns[4], UserIdentitiesColumns[5]},
			},
			{
				Name:    "useridentity_user_biz_id",
				Unique:  false,
				Columns: []*schema.Column{UserIdentitiesColumns[4]},
			},
			{
				Name:    "useridentity_provider_provider_email_normalized",
				Unique:  false,
				Columns: []*schema.Column{UserIdentitiesColumns[5], UserIdentitiesColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppSettingsTable,
		AuthActionTokensTable,
		AuthRefreshTokensTable,
		OauthLoginStatesTable,
		TodosTable,
		UsersTable,
		UserIdentitiesTable,
	}
)

func init() {
}
