// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/conversationmember"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
)

// ConversationMemberUpdate is the builder for updating ConversationMember entities.
type ConversationMemberUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMemberMutation
}

// Where appends a list predicates to the ConversationMemberUpdate builder.
func (_u *ConversationMemberUpdate) Where(ps ...predicate.ConversationMember) *ConversationMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationMemberUpdate) SetUpdatedAt(v time.Time) *ConversationMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMemberUpdate) SetConversationID(v int64) *ConversationMemberUpdate {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableConversationID(v *int64) *ConversationMemberUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *ConversationMemberUpdate) AddConversationID(v int64) *ConversationMemberUpdate {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetMemberType sets the "member_type" field.
func (_u *ConversationMemberUpdate) SetMemberType(v int8) *ConversationMemberUpdate {
	_u.mutation.ResetMemberType()
	_u.mutation.SetMemberType(v)
	return _u
}

// SetNillableMemberType sets the "member_type" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableMemberType(v *int8) *ConversationMemberUpdate {
	if v != nil {
		_u.SetMemberType(*v)
	}
	return _u
}

// AddMemberType adds value to the "member_type" field.
func (_u *ConversationMemberUpdate) AddMemberType(v int8) *ConversationMemberUpdate {
	_u.mutation.AddMemberType(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *ConversationMemberUpdate) SetMemberID(v int64) *ConversationMemberUpdate {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableMemberID(v *int64) *ConversationMemberUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *ConversationMemberUpdate) AddMemberID(v int64) *ConversationMemberUpdate {
	_u.mutation.AddMemberID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *ConversationMemberUpdate) SetRole(v int8) *ConversationMemberUpdate {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableRole(v *int8) *ConversationMemberUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *ConversationMemberUpdate) AddRole(v int8) *ConversationMemberUpdate {
	_u.mutation.AddRole(v)
	return _u
}

// SetReadSeq sets the "read_seq" field.
func (_u *ConversationMemberUpdate) SetReadSeq(v int64) *ConversationMemberUpdate {
	_u.mutation.ResetReadSeq()
	_u.mutation.SetReadSeq(v)
	return _u
}

// SetNillableReadSeq sets the "read_seq" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableReadSeq(v *int64) *ConversationMemberUpdate {
	if v != nil {
		_u.SetReadSeq(*v)
	}
	return _u
}

// AddReadSeq adds value to the "read_seq" field.
func (_u *ConversationMemberUpdate) AddReadSeq(v int64) *ConversationMemberUpdate {
	_u.mutation.AddReadSeq(v)
	return _u
}

// SetLastReadAt sets the "last_read_at" field.
func (_u *ConversationMemberUpdate) SetLastReadAt(v time.Time) *ConversationMemberUpdate {
	_u.mutation.SetLastReadAt(v)
	return _u
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableLastReadAt(v *time.Time) *ConversationMemberUpdate {
	if v != nil {
		_u.SetLastReadAt(*v)
	}
	return _u
}

// ClearLastReadAt clears the value of the "last_read_at" field.
func (_u *ConversationMemberUpdate) ClearLastReadAt() *ConversationMemberUpdate {
	_u.mutation.ClearLastReadAt()
	return _u
}

// SetIsMuted sets the "is_muted" field.
func (_u *ConversationMemberUpdate) SetIsMuted(v bool) *ConversationMemberUpdate {
	_u.mutation.SetIsMuted(v)
	return _u
}

// SetNillableIsMuted sets the "is_muted" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableIsMuted(v *bool) *ConversationMemberUpdate {
	if v != nil {
		_u.SetIsMuted(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *ConversationMemberUpdate) SetIsPinned(v bool) *ConversationMemberUpdate {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableIsPinned(v *bool) *ConversationMemberUpdate {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationMemberUpdate) SetStatus(v int8) *ConversationMemberUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableStatus(v *int8) *ConversationMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ConversationMemberUpdate) AddStatus(v int8) *ConversationMemberUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ConversationMemberUpdate) SetJoinedAt(v time.Time) *ConversationMemberUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ConversationMemberUpdate) SetNillableJoinedAt(v *time.Time) *ConversationMemberUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// Mutation returns the ConversationMemberMutation object of the builder.
func (_u *ConversationMemberUpdate) Mutation() *ConversationMemberMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversationmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ConversationMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(conversationmember.Table, conversationmember.Columns, sqlgraph.NewFieldSpec(conversationmember.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversationmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(conversationmember.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(conversationmember.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberType(); ok {
		_spec.SetField(conversationmember.FieldMemberType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMemberType(); ok {
		_spec.AddField(conversationmember.FieldMemberType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(conversationmember.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(conversationmember.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(conversationmember.FieldRole, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(conversationmember.FieldRole, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ReadSeq(); ok {
		_spec.SetField(conversationmember.FieldReadSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReadSeq(); ok {
		_spec.AddField(conversationmember.FieldReadSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastReadAt(); ok {
		_spec.SetField(conversationmember.FieldLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.LastReadAtCleared() {
		_spec.ClearField(conversationmember.FieldLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsMuted(); ok {
		_spec.SetField(conversationmember.FieldIsMuted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(conversationmember.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversationmember.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(conversationmember.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(conversationmember.FieldJoinedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationMemberUpdateOne is the builder for updating a single ConversationMember entity.
type ConversationMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMemberMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationMemberUpdateOne) SetUpdatedAt(v time.Time) *ConversationMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMemberUpdateOne) SetConversationID(v int64) *ConversationMemberUpdateOne {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableConversationID(v *int64) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *ConversationMemberUpdateOne) AddConversationID(v int64) *ConversationMemberUpdateOne {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetMemberType sets the "member_type" field.
func (_u *ConversationMemberUpdateOne) SetMemberType(v int8) *ConversationMemberUpdateOne {
	_u.mutation.ResetMemberType()
	_u.mutation.SetMemberType(v)
	return _u
}

// SetNillableMemberType sets the "member_type" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableMemberType(v *int8) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetMemberType(*v)
	}
	return _u
}

// AddMemberType adds value to the "member_type" field.
func (_u *ConversationMemberUpdateOne) AddMemberType(v int8) *ConversationMemberUpdateOne {
	_u.mutation.AddMemberType(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *ConversationMemberUpdateOne) SetMemberID(v int64) *ConversationMemberUpdateOne {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableMemberID(v *int64) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *ConversationMemberUpdateOne) AddMemberID(v int64) *ConversationMemberUpdateOne {
	_u.mutation.AddMemberID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *ConversationMemberUpdateOne) SetRole(v int8) *ConversationMemberUpdateOne {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableRole(v *int8) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *ConversationMemberUpdateOne) AddRole(v int8) *ConversationMemberUpdateOne {
	_u.mutation.AddRole(v)
	return _u
}

// SetReadSeq sets the "read_seq" field.
func (_u *ConversationMemberUpdateOne) SetReadSeq(v int64) *ConversationMemberUpdateOne {
	_u.mutation.ResetReadSeq()
	_u.mutation.SetReadSeq(v)
	return _u
}

// SetNillableReadSeq sets the "read_seq" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableReadSeq(v *int64) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetReadSeq(*v)
	}
	return _u
}

// AddReadSeq adds value to the "read_seq" field.
func (_u *ConversationMemberUpdateOne) AddReadSeq(v int64) *ConversationMemberUpdateOne {
	_u.mutation.AddReadSeq(v)
	return _u
}

// SetLastReadAt sets the "last_read_at" field.
func (_u *ConversationMemberUpdateOne) SetLastReadAt(v time.Time) *ConversationMemberUpdateOne {
	_u.mutation.SetLastReadAt(v)
	return _u
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableLastReadAt(v *time.Time) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetLastReadAt(*v)
	}
	return _u
}

// ClearLastReadAt clears the value of the "last_read_at" field.
func (_u *ConversationMemberUpdateOne) ClearLastReadAt() *ConversationMemberUpdateOne {
	_u.mutation.ClearLastReadAt()
	return _u
}

// SetIsMuted sets the "is_muted" field.
func (_u *ConversationMemberUpdateOne) SetIsMuted(v bool) *ConversationMemberUpdateOne {
	_u.mutation.SetIsMuted(v)
	return _u
}

// SetNillableIsMuted sets the "is_muted" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableIsMuted(v *bool) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetIsMuted(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *ConversationMemberUpdateOne) SetIsPinned(v bool) *ConversationMemberUpdateOne {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableIsPinned(v *bool) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationMemberUpdateOne) SetStatus(v int8) *ConversationMemberUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableStatus(v *int8) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ConversationMemberUpdateOne) AddStatus(v int8) *ConversationMemberUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ConversationMemberUpdateOne) SetJoinedAt(v time.Time) *ConversationMemberUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ConversationMemberUpdateOne) SetNillableJoinedAt(v *time.Time) *ConversationMemberUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// Mutation returns the ConversationMemberMutation object of the builder.
func (_u *ConversationMemberUpdateOne) Mutation() *ConversationMemberMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConversationMemberUpdate builder.
func (_u *ConversationMemberUpdateOne) Where(ps ...predicate.ConversationMember) *ConversationMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationMemberUpdateOne) Select(field string, fields ...string) *ConversationMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConversationMember entity.
func (_u *ConversationMemberUpdateOne) Save(ctx context.Context) (*ConversationMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMemberUpdateOne) SaveX(ctx context.Context) *ConversationMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversationmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ConversationMemberUpdateOne) sqlSave(ctx context.Context) (_node *ConversationMember, err error) {
	_spec := sqlgraph.NewUpdateSpec(conversationmember.Table, conversationmember.Columns, sqlgraph.NewFieldSpec(conversationmember.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConversationMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversationmember.FieldID)
		for _, f := range fields {
			if !conversationmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversationmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversationmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(conversationmember.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(conversationmember.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberType(); ok {
		_spec.SetField(conversationmember.FieldMemberType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMemberType(); ok {
		_spec.AddField(conversationmember.FieldMemberType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(conversationmember.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(conversationmember.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(conversationmember.FieldRole, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(conversationmember.FieldRole, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ReadSeq(); ok {
		_spec.SetField(conversationmember.FieldReadSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReadSeq(); ok {
		_spec.AddField(conversationmember.FieldReadSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastReadAt(); ok {
		_spec.SetField(conversationmember.FieldLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.LastReadAtCleared() {
		_spec.ClearField(conversationmember.FieldLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsMuted(); ok {
		_spec.SetField(conversationmember.FieldIsMuted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(conversationmember.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversationmember.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(conversationmember.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(conversationmember.FieldJoinedAt, field.TypeTime, value)
	}
	_node = &ConversationMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
