// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/conversationmember"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
)

// ConversationMemberDelete is the builder for deleting a ConversationMember entity.
type ConversationMemberDelete struct {
	config
	hooks    []Hook
	mutation *ConversationMemberMutation
}

// Where appends a list predicates to the ConversationMemberDelete builder.
func (_d *ConversationMemberDelete) Where(ps ...predicate.ConversationMember) *ConversationMemberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ConversationMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ConversationMemberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ConversationMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(conversationmember.Table, sqlgraph.NewFieldSpec(conversationmember.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ConversationMemberDeleteOne is the builder for deleting a single ConversationMember entity.
type ConversationMemberDeleteOne struct {
	_d *ConversationMemberDelete
}

// Where appends a list predicates to the ConversationMemberDelete builder.
func (_d *ConversationMemberDeleteOne) Where(ps ...predicate.ConversationMember) *ConversationMemberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ConversationMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{conversationmember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ConversationMemberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
