// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/conversation"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
)

// ConversationUpdate is the builder for updating Conversation entities.
type ConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMutation
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdate) Where(ps ...predicate.Conversation) *ConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationUpdate) SetUpdatedAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *ConversationUpdate) SetWorkspaceID(v int64) *ConversationUpdate {
	_u.mutation.ResetWorkspaceID()
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableWorkspaceID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// AddWorkspaceID adds value to the "workspace_id" field.
func (_u *ConversationUpdate) AddWorkspaceID(v int64) *ConversationUpdate {
	_u.mutation.AddWorkspaceID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ConversationUpdate) SetType(v int8) *ConversationUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableType(v *int8) *ConversationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *ConversationUpdate) AddType(v int8) *ConversationUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ConversationUpdate) SetVisibility(v int8) *ConversationUpdate {
	_u.mutation.ResetVisibility()
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableVisibility(v *int8) *ConversationUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddVisibility adds value to the "visibility" field.
func (_u *ConversationUpdate) AddVisibility(v int8) *ConversationUpdate {
	_u.mutation.AddVisibility(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ConversationUpdate) SetName(v string) *ConversationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableName(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ConversationUpdate) ClearName() *ConversationUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetTopic sets the "topic" field.
func (_u *ConversationUpdate) SetTopic(v string) *ConversationUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableTopic(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// ClearTopic clears the value of the "topic" field.
func (_u *ConversationUpdate) ClearTopic() *ConversationUpdate {
	_u.mutation.ClearTopic()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *ConversationUpdate) SetCreatorID(v int64) *ConversationUpdate {
	_u.mutation.ResetCreatorID()
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableCreatorID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// AddCreatorID adds value to the "creator_id" field.
func (_u *ConversationUpdate) AddCreatorID(v int64) *ConversationUpdate {
	_u.mutation.AddCreatorID(v)
	return _u
}

// SetDmKey sets the "dm_key" field.
func (_u *ConversationUpdate) SetDmKey(v string) *ConversationUpdate {
	_u.mutation.SetDmKey(v)
	return _u
}

// SetNillableDmKey sets the "dm_key" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableDmKey(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetDmKey(*v)
	}
	return _u
}

// ClearDmKey clears the value of the "dm_key" field.
func (_u *ConversationUpdate) ClearDmKey() *ConversationUpdate {
	_u.mutation.ClearDmKey()
	return _u
}

// SetLastSeq sets the "last_seq" field.
func (_u *ConversationUpdate) SetLastSeq(v int64) *ConversationUpdate {
	_u.mutation.ResetLastSeq()
	_u.mutation.SetLastSeq(v)
	return _u
}

// SetNillableLastSeq sets the "last_seq" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastSeq(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetLastSeq(*v)
	}
	return _u
}

// AddLastSeq adds value to the "last_seq" field.
func (_u *ConversationUpdate) AddLastSeq(v int64) *ConversationUpdate {
	_u.mutation.AddLastSeq(v)
	return _u
}

// SetLastMsgID sets the "last_msg_id" field.
func (_u *ConversationUpdate) SetLastMsgID(v int64) *ConversationUpdate {
	_u.mutation.ResetLastMsgID()
	_u.mutation.SetLastMsgID(v)
	return _u
}

// SetNillableLastMsgID sets the "last_msg_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastMsgID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetLastMsgID(*v)
	}
	return _u
}

// AddLastMsgID adds value to the "last_msg_id" field.
func (_u *ConversationUpdate) AddLastMsgID(v int64) *ConversationUpdate {
	_u.mutation.AddLastMsgID(v)
	return _u
}

// SetLastMsgDigest sets the "last_msg_digest" field.
func (_u *ConversationUpdate) SetLastMsgDigest(v string) *ConversationUpdate {
	_u.mutation.SetLastMsgDigest(v)
	return _u
}

// SetNillableLastMsgDigest sets the "last_msg_digest" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastMsgDigest(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetLastMsgDigest(*v)
	}
	return _u
}

// ClearLastMsgDigest clears the value of the "last_msg_digest" field.
func (_u *ConversationUpdate) ClearLastMsgDigest() *ConversationUpdate {
	_u.mutation.ClearLastMsgDigest()
	return _u
}

// SetLastMsgAt sets the "last_msg_at" field.
func (_u *ConversationUpdate) SetLastMsgAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetLastMsgAt(v)
	return _u
}

// SetNillableLastMsgAt sets the "last_msg_at" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastMsgAt(v *time.Time) *ConversationUpdate {
	if v != nil {
		_u.SetLastMsgAt(*v)
	}
	return _u
}

// ClearLastMsgAt clears the value of the "last_msg_at" field.
func (_u *ConversationUpdate) ClearLastMsgAt() *ConversationUpdate {
	_u.mutation.ClearLastMsgAt()
	return _u
}

// SetMemberCount sets the "member_count" field.
func (_u *ConversationUpdate) SetMemberCount(v int) *ConversationUpdate {
	_u.mutation.ResetMemberCount()
	_u.mutation.SetMemberCount(v)
	return _u
}

// SetNillableMemberCount sets the "member_count" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableMemberCount(v *int) *ConversationUpdate {
	if v != nil {
		_u.SetMemberCount(*v)
	}
	return _u
}

// AddMemberCount adds value to the "member_count" field.
func (_u *ConversationUpdate) AddMemberCount(v int) *ConversationUpdate {
	_u.mutation.AddMemberCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationUpdate) SetStatus(v int8) *ConversationUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableStatus(v *int8) *ConversationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ConversationUpdate) AddStatus(v int8) *ConversationUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ConversationUpdate) SetMetadata(v map[string]interface{}) *ConversationUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ConversationUpdate) ClearMetadata() *ConversationUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdate) Mutation() *ConversationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := conversation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Conversation.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Topic(); ok {
		if err := conversation.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "Conversation.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DmKey(); ok {
		if err := conversation.DmKeyValidator(v); err != nil {
			return &ValidationError{Name: "dm_key", err: fmt.Errorf(`ent: validator failed for field "Conversation.dm_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMsgDigest(); ok {
		if err := conversation.LastMsgDigestValidator(v); err != nil {
			return &ValidationError{Name: "last_msg_digest", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_msg_digest": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(conversation.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(conversation.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(conversation.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(conversation.FieldVisibility, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedVisibility(); ok {
		_spec.AddField(conversation.FieldVisibility, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(conversation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(conversation.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(conversation.FieldTopic, field.TypeString, value)
	}
	if _u.mutation.TopicCleared() {
		_spec.ClearField(conversation.FieldTopic, field.TypeString)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(conversation.FieldCreatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatorID(); ok {
		_spec.AddField(conversation.FieldCreatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DmKey(); ok {
		_spec.SetField(conversation.FieldDmKey, field.TypeString, value)
	}
	if _u.mutation.DmKeyCleared() {
		_spec.ClearField(conversation.FieldDmKey, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeq(); ok {
		_spec.SetField(conversation.FieldLastSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastSeq(); ok {
		_spec.AddField(conversation.FieldLastSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastMsgID(); ok {
		_spec.SetField(conversation.FieldLastMsgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMsgID(); ok {
		_spec.AddField(conversation.FieldLastMsgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastMsgDigest(); ok {
		_spec.SetField(conversation.FieldLastMsgDigest, field.TypeString, value)
	}
	if _u.mutation.LastMsgDigestCleared() {
		_spec.ClearField(conversation.FieldLastMsgDigest, field.TypeString)
	}
	if value, ok := _u.mutation.LastMsgAt(); ok {
		_spec.SetField(conversation.FieldLastMsgAt, field.TypeTime, value)
	}
	if _u.mutation.LastMsgAtCleared() {
		_spec.ClearField(conversation.FieldLastMsgAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MemberCount(); ok {
		_spec.SetField(conversation.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberCount(); ok {
		_spec.AddField(conversation.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(conversation.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(conversation.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(conversation.FieldMetadata, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationUpdateOne is the builder for updating a single Conversation entity.
type ConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationUpdateOne) SetUpdatedAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *ConversationUpdateOne) SetWorkspaceID(v int64) *ConversationUpdateOne {
	_u.mutation.ResetWorkspaceID()
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableWorkspaceID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// AddWorkspaceID adds value to the "workspace_id" field.
func (_u *ConversationUpdateOne) AddWorkspaceID(v int64) *ConversationUpdateOne {
	_u.mutation.AddWorkspaceID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ConversationUpdateOne) SetType(v int8) *ConversationUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableType(v *int8) *ConversationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *ConversationUpdateOne) AddType(v int8) *ConversationUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ConversationUpdateOne) SetVisibility(v int8) *ConversationUpdateOne {
	_u.mutation.ResetVisibility()
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableVisibility(v *int8) *ConversationUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddVisibility adds value to the "visibility" field.
func (_u *ConversationUpdateOne) AddVisibility(v int8) *ConversationUpdateOne {
	_u.mutation.AddVisibility(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ConversationUpdateOne) SetName(v string) *ConversationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableName(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ConversationUpdateOne) ClearName() *ConversationUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetTopic sets the "topic" field.
func (_u *ConversationUpdateOne) SetTopic(v string) *ConversationUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableTopic(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// ClearTopic clears the value of the "topic" field.
func (_u *ConversationUpdateOne) ClearTopic() *ConversationUpdateOne {
	_u.mutation.ClearTopic()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *ConversationUpdateOne) SetCreatorID(v int64) *ConversationUpdateOne {
	_u.mutation.ResetCreatorID()
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableCreatorID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// AddCreatorID adds value to the "creator_id" field.
func (_u *ConversationUpdateOne) AddCreatorID(v int64) *ConversationUpdateOne {
	_u.mutation.AddCreatorID(v)
	return _u
}

// SetDmKey sets the "dm_key" field.
func (_u *ConversationUpdateOne) SetDmKey(v string) *ConversationUpdateOne {
	_u.mutation.SetDmKey(v)
	return _u
}

// SetNillableDmKey sets the "dm_key" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableDmKey(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetDmKey(*v)
	}
	return _u
}

// ClearDmKey clears the value of the "dm_key" field.
func (_u *ConversationUpdateOne) ClearDmKey() *ConversationUpdateOne {
	_u.mutation.ClearDmKey()
	return _u
}

// SetLastSeq sets the "last_seq" field.
func (_u *ConversationUpdateOne) SetLastSeq(v int64) *ConversationUpdateOne {
	_u.mutation.ResetLastSeq()
	_u.mutation.SetLastSeq(v)
	return _u
}

// SetNillableLastSeq sets the "last_seq" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastSeq(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastSeq(*v)
	}
	return _u
}

// AddLastSeq adds value to the "last_seq" field.
func (_u *ConversationUpdateOne) AddLastSeq(v int64) *ConversationUpdateOne {
	_u.mutation.AddLastSeq(v)
	return _u
}

// SetLastMsgID sets the "last_msg_id" field.
func (_u *ConversationUpdateOne) SetLastMsgID(v int64) *ConversationUpdateOne {
	_u.mutation.ResetLastMsgID()
	_u.mutation.SetLastMsgID(v)
	return _u
}

// SetNillableLastMsgID sets the "last_msg_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastMsgID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastMsgID(*v)
	}
	return _u
}

// AddLastMsgID adds value to the "last_msg_id" field.
func (_u *ConversationUpdateOne) AddLastMsgID(v int64) *ConversationUpdateOne {
	_u.mutation.AddLastMsgID(v)
	return _u
}

// SetLastMsgDigest sets the "last_msg_digest" field.
func (_u *ConversationUpdateOne) SetLastMsgDigest(v string) *ConversationUpdateOne {
	_u.mutation.SetLastMsgDigest(v)
	return _u
}

// SetNillableLastMsgDigest sets the "last_msg_digest" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastMsgDigest(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastMsgDigest(*v)
	}
	return _u
}

// ClearLastMsgDigest clears the value of the "last_msg_digest" field.
func (_u *ConversationUpdateOne) ClearLastMsgDigest() *ConversationUpdateOne {
	_u.mutation.ClearLastMsgDigest()
	return _u
}

// SetLastMsgAt sets the "last_msg_at" field.
func (_u *ConversationUpdateOne) SetLastMsgAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetLastMsgAt(v)
	return _u
}

// SetNillableLastMsgAt sets the "last_msg_at" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastMsgAt(v *time.Time) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastMsgAt(*v)
	}
	return _u
}

// ClearLastMsgAt clears the value of the "last_msg_at" field.
func (_u *ConversationUpdateOne) ClearLastMsgAt() *ConversationUpdateOne {
	_u.mutation.ClearLastMsgAt()
	return _u
}

// SetMemberCount sets the "member_count" field.
func (_u *ConversationUpdateOne) SetMemberCount(v int) *ConversationUpdateOne {
	_u.mutation.ResetMemberCount()
	_u.mutation.SetMemberCount(v)
	return _u
}

// SetNillableMemberCount sets the "member_count" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableMemberCount(v *int) *ConversationUpdateOne {
	if v != nil {
		_u.SetMemberCount(*v)
	}
	return _u
}

// AddMemberCount adds value to the "member_count" field.
func (_u *ConversationUpdateOne) AddMemberCount(v int) *ConversationUpdateOne {
	_u.mutation.AddMemberCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationUpdateOne) SetStatus(v int8) *ConversationUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableStatus(v *int8) *ConversationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ConversationUpdateOne) AddStatus(v int8) *ConversationUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ConversationUpdateOne) SetMetadata(v map[string]interface{}) *ConversationUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ConversationUpdateOne) ClearMetadata() *ConversationUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdateOne) Mutation() *ConversationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdateOne) Where(ps ...predicate.Conversation) *ConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationUpdateOne) Select(field string, fields ...string) *ConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Conversation entity.
func (_u *ConversationUpdateOne) Save(ctx context.Context) (*Conversation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdateOne) SaveX(ctx context.Context) *Conversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := conversation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Conversation.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Topic(); ok {
		if err := conversation.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "Conversation.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DmKey(); ok {
		if err := conversation.DmKeyValidator(v); err != nil {
			return &ValidationError{Name: "dm_key", err: fmt.Errorf(`ent: validator failed for field "Conversation.dm_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMsgDigest(); ok {
		if err := conversation.LastMsgDigestValidator(v); err != nil {
			return &ValidationError{Name: "last_msg_digest", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_msg_digest": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationUpdateOne) sqlSave(ctx context.Context) (_node *Conversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Conversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversation.FieldID)
		for _, f := range fields {
			if !conversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(conversation.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(conversation.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(conversation.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(conversation.FieldVisibility, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedVisibility(); ok {
		_spec.AddField(conversation.FieldVisibility, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(conversation.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(conversation.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(conversation.FieldTopic, field.TypeString, value)
	}
	if _u.mutation.TopicCleared() {
		_spec.ClearField(conversation.FieldTopic, field.TypeString)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(conversation.FieldCreatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatorID(); ok {
		_spec.AddField(conversation.FieldCreatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DmKey(); ok {
		_spec.SetField(conversation.FieldDmKey, field.TypeString, value)
	}
	if _u.mutation.DmKeyCleared() {
		_spec.ClearField(conversation.FieldDmKey, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeq(); ok {
		_spec.SetField(conversation.FieldLastSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastSeq(); ok {
		_spec.AddField(conversation.FieldLastSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastMsgID(); ok {
		_spec.SetField(conversation.FieldLastMsgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMsgID(); ok {
		_spec.AddField(conversation.FieldLastMsgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastMsgDigest(); ok {
		_spec.SetField(conversation.FieldLastMsgDigest, field.TypeString, value)
	}
	if _u.mutation.LastMsgDigestCleared() {
		_spec.ClearField(conversation.FieldLastMsgDigest, field.TypeString)
	}
	if value, ok := _u.mutation.LastMsgAt(); ok {
		_spec.SetField(conversation.FieldLastMsgAt, field.TypeTime, value)
	}
	if _u.mutation.LastMsgAtCleared() {
		_spec.ClearField(conversation.FieldLastMsgAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MemberCount(); ok {
		_spec.SetField(conversation.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberCount(); ok {
		_spec.AddField(conversation.FieldMemberCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(conversation.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(conversation.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(conversation.FieldMetadata, field.TypeJSON)
	}
	_node = &Conversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
