// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/messagechange"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
)

// MessageChangeUpdate is the builder for updating MessageChange entities.
type MessageChangeUpdate struct {
	config
	hooks    []Hook
	mutation *MessageChangeMutation
}

// Where appends a list predicates to the MessageChangeUpdate builder.
func (_u *MessageChangeUpdate) Where(ps ...predicate.MessageChange) *MessageChangeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageChangeUpdate) SetUpdatedAt(v time.Time) *MessageChangeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *MessageChangeUpdate) SetConversationID(v int64) *MessageChangeUpdate {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *MessageChangeUpdate) SetNillableConversationID(v *int64) *MessageChangeUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *MessageChangeUpdate) AddConversationID(v int64) *MessageChangeUpdate {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetChangeSeq sets the "change_seq" field.
func (_u *MessageChangeUpdate) SetChangeSeq(v int64) *MessageChangeUpdate {
	_u.mutation.ResetChangeSeq()
	_u.mutation.SetChangeSeq(v)
	return _u
}

// SetNillableChangeSeq sets the "change_seq" field if the given value is not nil.
func (_u *MessageChangeUpdate) SetNillableChangeSeq(v *int64) *MessageChangeUpdate {
	if v != nil {
		_u.SetChangeSeq(*v)
	}
	return _u
}

// AddChangeSeq adds value to the "change_seq" field.
func (_u *MessageChangeUpdate) AddChangeSeq(v int64) *MessageChangeUpdate {
	_u.mutation.AddChangeSeq(v)
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *MessageChangeUpdate) SetChangeType(v int8) *MessageChangeUpdate {
	_u.mutation.ResetChangeType()
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *MessageChangeUpdate) SetNillableChangeType(v *int8) *MessageChangeUpdate {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// AddChangeType adds value to the "change_type" field.
func (_u *MessageChangeUpdate) AddChangeType(v int8) *MessageChangeUpdate {
	_u.mutation.AddChangeType(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MessageChangeUpdate) SetMessageID(v int64) *MessageChangeUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageChangeUpdate) SetNillableMessageID(v *int64) *MessageChangeUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *MessageChangeUpdate) AddMessageID(v int64) *MessageChangeUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *MessageChangeUpdate) SetActorID(v int64) *MessageChangeUpdate {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *MessageChangeUpdate) SetNillableActorID(v *int64) *MessageChangeUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *MessageChangeUpdate) AddActorID(v int64) *MessageChangeUpdate {
	_u.mutation.AddActorID(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MessageChangeUpdate) SetPayload(v map[string]interface{}) *MessageChangeUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MessageChangeUpdate) ClearPayload() *MessageChangeUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// Mutation returns the MessageChangeMutation object of the builder.
func (_u *MessageChangeUpdate) Mutation() *MessageChangeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageChangeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageChangeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageChangeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageChangeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageChangeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := messagechange.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MessageChangeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(messagechange.Table, messagechange.Columns, sqlgraph.NewFieldSpec(messagechange.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(messagechange.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(messagechange.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(messagechange.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChangeSeq(); ok {
		_spec.SetField(messagechange.FieldChangeSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChangeSeq(); ok {
		_spec.AddField(messagechange.FieldChangeSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(messagechange.FieldChangeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedChangeType(); ok {
		_spec.AddField(messagechange.FieldChangeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(messagechange.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(messagechange.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(messagechange.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(messagechange.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(messagechange.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(messagechange.FieldPayload, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagechange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageChangeUpdateOne is the builder for updating a single MessageChange entity.
type MessageChangeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageChangeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageChangeUpdateOne) SetUpdatedAt(v time.Time) *MessageChangeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *MessageChangeUpdateOne) SetConversationID(v int64) *MessageChangeUpdateOne {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *MessageChangeUpdateOne) SetNillableConversationID(v *int64) *MessageChangeUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *MessageChangeUpdateOne) AddConversationID(v int64) *MessageChangeUpdateOne {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetChangeSeq sets the "change_seq" field.
func (_u *MessageChangeUpdateOne) SetChangeSeq(v int64) *MessageChangeUpdateOne {
	_u.mutation.ResetChangeSeq()
	_u.mutation.SetChangeSeq(v)
	return _u
}

// SetNillableChangeSeq sets the "change_seq" field if the given value is not nil.
func (_u *MessageChangeUpdateOne) SetNillableChangeSeq(v *int64) *MessageChangeUpdateOne {
	if v != nil {
		_u.SetChangeSeq(*v)
	}
	return _u
}

// AddChangeSeq adds value to the "change_seq" field.
func (_u *MessageChangeUpdateOne) AddChangeSeq(v int64) *MessageChangeUpdateOne {
	_u.mutation.AddChangeSeq(v)
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *MessageChangeUpdateOne) SetChangeType(v int8) *MessageChangeUpdateOne {
	_u.mutation.ResetChangeType()
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *MessageChangeUpdateOne) SetNillableChangeType(v *int8) *MessageChangeUpdateOne {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// AddChangeType adds value to the "change_type" field.
func (_u *MessageChangeUpdateOne) AddChangeType(v int8) *MessageChangeUpdateOne {
	_u.mutation.AddChangeType(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MessageChangeUpdateOne) SetMessageID(v int64) *MessageChangeUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageChangeUpdateOne) SetNillableMessageID(v *int64) *MessageChangeUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *MessageChangeUpdateOne) AddMessageID(v int64) *MessageChangeUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *MessageChangeUpdateOne) SetActorID(v int64) *MessageChangeUpdateOne {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *MessageChangeUpdateOne) SetNillableActorID(v *int64) *MessageChangeUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *MessageChangeUpdateOne) AddActorID(v int64) *MessageChangeUpdateOne {
	_u.mutation.AddActorID(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MessageChangeUpdateOne) SetPayload(v map[string]interface{}) *MessageChangeUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MessageChangeUpdateOne) ClearPayload() *MessageChangeUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// Mutation returns the MessageChangeMutation object of the builder.
func (_u *MessageChangeUpdateOne) Mutation() *MessageChangeMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageChangeUpdate builder.
func (_u *MessageChangeUpdateOne) Where(ps ...predicate.MessageChange) *MessageChangeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageChangeUpdateOne) Select(field string, fields ...string) *MessageChangeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MessageChange entity.
func (_u *MessageChangeUpdateOne) Save(ctx context.Context) (*MessageChange, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageChangeUpdateOne) SaveX(ctx context.Context) *MessageChange {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageChangeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageChangeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageChangeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := messagechange.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MessageChangeUpdateOne) sqlSave(ctx context.Context) (_node *MessageChange, err error) {
	_spec := sqlgraph.NewUpdateSpec(messagechange.Table, messagechange.Columns, sqlgraph.NewFieldSpec(messagechange.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageChange.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagechange.FieldID)
		for _, f := range fields {
			if !messagechange.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messagechange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(messagechange.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(messagechange.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(messagechange.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChangeSeq(); ok {
		_spec.SetField(messagechange.FieldChangeSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChangeSeq(); ok {
		_spec.AddField(messagechange.FieldChangeSeq, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(messagechange.FieldChangeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedChangeType(); ok {
		_spec.AddField(messagechange.FieldChangeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(messagechange.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(messagechange.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(messagechange.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(messagechange.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(messagechange.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(messagechange.FieldPayload, field.TypeJSON)
	}
	_node = &MessageChange{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagechange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
