// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/oauthloginstate"
)

// OAuthLoginStateCreate is the builder for creating a OAuthLoginState entity.
type OAuthLoginStateCreate struct {
	config
	mutation *OAuthLoginStateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthLoginStateCreate) SetCreatedAt(v time.Time) *OAuthLoginStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthLoginStateCreate) SetNillableCreatedAt(v *time.Time) *OAuthLoginStateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthLoginStateCreate) SetUpdatedAt(v time.Time) *OAuthLoginStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthLoginStateCreate) SetNillableUpdatedAt(v *time.Time) *OAuthLoginStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStateHash sets the "state_hash" field.
func (_c *OAuthLoginStateCreate) SetStateHash(v string) *OAuthLoginStateCreate {
	_c.mutation.SetStateHash(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *OAuthLoginStateCreate) SetProvider(v string) *OAuthLoginStateCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetRedirectURL sets the "redirect_url" field.
func (_c *OAuthLoginStateCreate) SetRedirectURL(v string) *OAuthLoginStateCreate {
	_c.mutation.SetRedirectURL(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthLoginStateCreate) SetExpiresAt(v time.Time) *OAuthLoginStateCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *OAuthLoginStateCreate) SetConsumedAt(v time.Time) *OAuthLoginStateCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *OAuthLoginStateCreate) SetNillableConsumedAt(v *time.Time) *OAuthLoginStateCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// Mutation returns the OAuthLoginStateMutation object of the builder.
func (_c *OAuthLoginStateCreate) Mutation() *OAuthLoginStateMutation {
	return _c.mutation
}

// Save creates the OAuthLoginState in the database.
func (_c *OAuthLoginStateCreate) Save(ctx context.Context) (*OAuthLoginState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthLoginStateCreate) SaveX(ctx context.Context) *OAuthLoginState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthLoginStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthLoginStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthLoginStateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthloginstate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthloginstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthLoginStateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthLoginState.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthLoginState.updated_at"`)}
	}
	if _, ok := _c.mutation.StateHash(); !ok {
		return &ValidationError{Name: "state_hash", err: errors.New(`ent: missing required field "OAuthLoginState.state_hash"`)}
	}
	if v, ok := _c.mutation.StateHash(); ok {
		if err := oauthloginstate.StateHashValidator(v); err != nil {
			return &ValidationError{Name: "state_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthLoginState.state_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "OAuthLoginState.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := oauthloginstate.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthLoginState.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURL(); !ok {
		return &ValidationError{Name: "redirect_url", err: errors.New(`ent: missing required field "OAuthLoginState.redirect_url"`)}
	}
	if v, ok := _c.mutation.RedirectURL(); ok {
		if err := oauthloginstate.RedirectURLValidator(v); err != nil {
			return &ValidationError{Name: "redirect_url", err: fmt.Errorf(`ent: validator failed for field "OAuthLoginState.redirect_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthLoginState.expires_at"`)}
	}
	return nil
}

func (_c *OAuthLoginStateCreate) sqlSave(ctx context.Context) (*OAuthLoginState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthLoginStateCreate) createSpec() (*OAuthLoginState, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthLoginState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthloginstate.Table, sqlgraph.NewFieldSpec(oauthloginstate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthloginstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthloginstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.StateHash(); ok {
		_spec.SetField(oauthloginstate.FieldStateHash, field.TypeString, value)
		_node.StateHash = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(oauthloginstate.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.RedirectURL(); ok {
		_spec.SetField(oauthloginstate.FieldRedirectURL, field.TypeString, value)
		_node.RedirectURL = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthloginstate.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthloginstate.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	return _node, _spec
}

// OAuthLoginStateCreateBulk is the builder for creating many OAuthLoginState entities in bulk.
type OAuthLoginStateCreateBulk struct {
	config
	err      error
	builders []*OAuthLoginStateCreate
}

// Save creates the OAuthLoginState entities in the database.
func (_c *OAuthLoginStateCreateBulk) Save(ctx context.Context) ([]*OAuthLoginState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthLoginState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthLoginStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthLoginStateCreateBulk) SaveX(ctx context.Context) []*OAuthLoginState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthLoginStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthLoginStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
