// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/maguowei/gotobeta/internal/ent/oauthloginstate"
)

// OAuthLoginState is the model entity for the OAuthLoginState schema.
type OAuthLoginState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// StateHash holds the value of the "state_hash" field.
	StateHash string `json:"state_hash,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// RedirectURL holds the value of the "redirect_url" field.
	RedirectURL string `json:"redirect_url,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt   *time.Time `json:"consumed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthLoginState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthloginstate.FieldID:
			values[i] = new(sql.NullInt64)
		case oauthloginstate.FieldStateHash, oauthloginstate.FieldProvider, oauthloginstate.FieldRedirectURL:
			values[i] = new(sql.NullString)
		case oauthloginstate.FieldCreatedAt, oauthloginstate.FieldUpdatedAt, oauthloginstate.FieldExpiresAt, oauthloginstate.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthLoginState fields.
func (_m *OAuthLoginState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthloginstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case oauthloginstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthloginstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthloginstate.FieldStateHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_hash", values[i])
			} else if value.Valid {
				_m.StateHash = value.String
			}
		case oauthloginstate.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case oauthloginstate.FieldRedirectURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_url", values[i])
			} else if value.Valid {
				_m.RedirectURL = value.String
			}
		case oauthloginstate.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oauthloginstate.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthLoginState.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthLoginState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthLoginState.
// Note that you need to call OAuthLoginState.Unwrap() before calling this method if this OAuthLoginState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthLoginState) Update() *OAuthLoginStateUpdateOne {
	return NewOAuthLoginStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthLoginState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthLoginState) Unwrap() *OAuthLoginState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthLoginState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthLoginState) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthLoginState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("state_hash=")
	builder.WriteString(_m.StateHash)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("redirect_url=")
	builder.WriteString(_m.RedirectURL)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthLoginStates is a parsable slice of OAuthLoginState.
type OAuthLoginStates []*OAuthLoginState
