// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
	"github.com/maguowei/gotobeta/internal/ent/rbacuserrole"
)

// RbacUserRoleDelete is the builder for deleting a RbacUserRole entity.
type RbacUserRoleDelete struct {
	config
	hooks    []Hook
	mutation *RbacUserRoleMutation
}

// Where appends a list predicates to the RbacUserRoleDelete builder.
func (_d *RbacUserRoleDelete) Where(ps ...predicate.RbacUserRole) *RbacUserRoleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RbacUserRoleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RbacUserRoleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RbacUserRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rbacuserrole.Table, sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RbacUserRoleDeleteOne is the builder for deleting a single RbacUserRole entity.
type RbacUserRoleDeleteOne struct {
	_d *RbacUserRoleDelete
}

// Where appends a list predicates to the RbacUserRoleDelete builder.
func (_d *RbacUserRoleDeleteOne) Where(ps ...predicate.RbacUserRole) *RbacUserRoleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RbacUserRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rbacuserrole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RbacUserRoleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
