// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermissionversion"
)

// RbacPermissionVersionCreate is the builder for creating a RbacPermissionVersion entity.
type RbacPermissionVersionCreate struct {
	config
	mutation *RbacPermissionVersionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RbacPermissionVersionCreate) SetCreatedAt(v time.Time) *RbacPermissionVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RbacPermissionVersionCreate) SetNillableCreatedAt(v *time.Time) *RbacPermissionVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RbacPermissionVersionCreate) SetUpdatedAt(v time.Time) *RbacPermissionVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RbacPermissionVersionCreate) SetNillableUpdatedAt(v *time.Time) *RbacPermissionVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *RbacPermissionVersionCreate) SetWorkspaceID(v int64) *RbacPermissionVersionCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetSubjectType sets the "subject_type" field.
func (_c *RbacPermissionVersionCreate) SetSubjectType(v int8) *RbacPermissionVersionCreate {
	_c.mutation.SetSubjectType(v)
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *RbacPermissionVersionCreate) SetSubjectID(v int64) *RbacPermissionVersionCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *RbacPermissionVersionCreate) SetVersion(v int64) *RbacPermissionVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *RbacPermissionVersionCreate) SetNillableVersion(v *int64) *RbacPermissionVersionCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// Mutation returns the RbacPermissionVersionMutation object of the builder.
func (_c *RbacPermissionVersionCreate) Mutation() *RbacPermissionVersionMutation {
	return _c.mutation
}

// Save creates the RbacPermissionVersion in the database.
func (_c *RbacPermissionVersionCreate) Save(ctx context.Context) (*RbacPermissionVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RbacPermissionVersionCreate) SaveX(ctx context.Context) *RbacPermissionVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacPermissionVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacPermissionVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RbacPermissionVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rbacpermissionversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rbacpermissionversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := rbacpermissionversion.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RbacPermissionVersionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RbacPermissionVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RbacPermissionVersion.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "RbacPermissionVersion.workspace_id"`)}
	}
	if _, ok := _c.mutation.SubjectType(); !ok {
		return &ValidationError{Name: "subject_type", err: errors.New(`ent: missing required field "RbacPermissionVersion.subject_type"`)}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "RbacPermissionVersion.subject_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "RbacPermissionVersion.version"`)}
	}
	return nil
}

func (_c *RbacPermissionVersionCreate) sqlSave(ctx context.Context) (*RbacPermissionVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RbacPermissionVersionCreate) createSpec() (*RbacPermissionVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &RbacPermissionVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rbacpermissionversion.Table, sqlgraph.NewFieldSpec(rbacpermissionversion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rbacpermissionversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermissionversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(rbacpermissionversion.FieldWorkspaceID, field.TypeInt64, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.SubjectType(); ok {
		_spec.SetField(rbacpermissionversion.FieldSubjectType, field.TypeInt8, value)
		_node.SubjectType = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(rbacpermissionversion.FieldSubjectID, field.TypeInt64, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(rbacpermissionversion.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	return _node, _spec
}

// RbacPermissionVersionCreateBulk is the builder for creating many RbacPermissionVersion entities in bulk.
type RbacPermissionVersionCreateBulk struct {
	config
	err      error
	builders []*RbacPermissionVersionCreate
}

// Save creates the RbacPermissionVersion entities in the database.
func (_c *RbacPermissionVersionCreateBulk) Save(ctx context.Context) ([]*RbacPermissionVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RbacPermissionVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RbacPermissionVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RbacPermissionVersionCreateBulk) SaveX(ctx context.Context) []*RbacPermissionVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacPermissionVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacPermissionVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
