// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermissionchangelog"
)

// RbacPermissionChangeLogCreate is the builder for creating a RbacPermissionChangeLog entity.
type RbacPermissionChangeLogCreate struct {
	config
	mutation *RbacPermissionChangeLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RbacPermissionChangeLogCreate) SetCreatedAt(v time.Time) *RbacPermissionChangeLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RbacPermissionChangeLogCreate) SetNillableCreatedAt(v *time.Time) *RbacPermissionChangeLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RbacPermissionChangeLogCreate) SetUpdatedAt(v time.Time) *RbacPermissionChangeLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RbacPermissionChangeLogCreate) SetNillableUpdatedAt(v *time.Time) *RbacPermissionChangeLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBizID sets the "biz_id" field.
func (_c *RbacPermissionChangeLogCreate) SetBizID(v int64) *RbacPermissionChangeLogCreate {
	_c.mutation.SetBizID(v)
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *RbacPermissionChangeLogCreate) SetWorkspaceID(v int64) *RbacPermissionChangeLogCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetChangeType sets the "change_type" field.
func (_c *RbacPermissionChangeLogCreate) SetChangeType(v int8) *RbacPermissionChangeLogCreate {
	_c.mutation.SetChangeType(v)
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *RbacPermissionChangeLogCreate) SetTargetType(v int8) *RbacPermissionChangeLogCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *RbacPermissionChangeLogCreate) SetTargetID(v int64) *RbacPermissionChangeLogCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_c *RbacPermissionChangeLogCreate) SetNillableTargetID(v *int64) *RbacPermissionChangeLogCreate {
	if v != nil {
		_c.SetTargetID(*v)
	}
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *RbacPermissionChangeLogCreate) SetOperatorID(v int64) *RbacPermissionChangeLogCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_c *RbacPermissionChangeLogCreate) SetNillableOperatorID(v *int64) *RbacPermissionChangeLogCreate {
	if v != nil {
		_c.SetOperatorID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RbacPermissionChangeLogCreate) SetRequestID(v string) *RbacPermissionChangeLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RbacPermissionChangeLogCreate) SetNillableRequestID(v *string) *RbacPermissionChangeLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetBeforeJSON sets the "before_json" field.
func (_c *RbacPermissionChangeLogCreate) SetBeforeJSON(v map[string]interface{}) *RbacPermissionChangeLogCreate {
	_c.mutation.SetBeforeJSON(v)
	return _c
}

// SetAfterJSON sets the "after_json" field.
func (_c *RbacPermissionChangeLogCreate) SetAfterJSON(v map[string]interface{}) *RbacPermissionChangeLogCreate {
	_c.mutation.SetAfterJSON(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *RbacPermissionChangeLogCreate) SetReason(v string) *RbacPermissionChangeLogCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *RbacPermissionChangeLogCreate) SetNillableReason(v *string) *RbacPermissionChangeLogCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// Mutation returns the RbacPermissionChangeLogMutation object of the builder.
func (_c *RbacPermissionChangeLogCreate) Mutation() *RbacPermissionChangeLogMutation {
	return _c.mutation
}

// Save creates the RbacPermissionChangeLog in the database.
func (_c *RbacPermissionChangeLogCreate) Save(ctx context.Context) (*RbacPermissionChangeLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RbacPermissionChangeLogCreate) SaveX(ctx context.Context) *RbacPermissionChangeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacPermissionChangeLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacPermissionChangeLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RbacPermissionChangeLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rbacpermissionchangelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rbacpermissionchangelog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		v := rbacpermissionchangelog.DefaultTargetID
		_c.mutation.SetTargetID(v)
	}
	if _, ok := _c.mutation.OperatorID(); !ok {
		v := rbacpermissionchangelog.DefaultOperatorID
		_c.mutation.SetOperatorID(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := rbacpermissionchangelog.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := rbacpermissionchangelog.DefaultReason
		_c.mutation.SetReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RbacPermissionChangeLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.updated_at"`)}
	}
	if _, ok := _c.mutation.BizID(); !ok {
		return &ValidationError{Name: "biz_id", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.biz_id"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.workspace_id"`)}
	}
	if _, ok := _c.mutation.ChangeType(); !ok {
		return &ValidationError{Name: "change_type", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.change_type"`)}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.target_type"`)}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.target_id"`)}
	}
	if _, ok := _c.mutation.OperatorID(); !ok {
		return &ValidationError{Name: "operator_id", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.operator_id"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := rbacpermissionchangelog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionChangeLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "RbacPermissionChangeLog.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := rbacpermissionchangelog.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionChangeLog.reason": %w`, err)}
		}
	}
	return nil
}

func (_c *RbacPermissionChangeLogCreate) sqlSave(ctx context.Context) (*RbacPermissionChangeLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RbacPermissionChangeLogCreate) createSpec() (*RbacPermissionChangeLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RbacPermissionChangeLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rbacpermissionchangelog.Table, sqlgraph.NewFieldSpec(rbacpermissionchangelog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.BizID(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldBizID, field.TypeInt64, value)
		_node.BizID = value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldWorkspaceID, field.TypeInt64, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.ChangeType(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldChangeType, field.TypeInt8, value)
		_node.ChangeType = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldTargetType, field.TypeInt8, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldTargetID, field.TypeInt64, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.OperatorID(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldOperatorID, field.TypeInt64, value)
		_node.OperatorID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.BeforeJSON(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldBeforeJSON, field.TypeJSON, value)
		_node.BeforeJSON = value
	}
	if value, ok := _c.mutation.AfterJSON(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldAfterJSON, field.TypeJSON, value)
		_node.AfterJSON = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(rbacpermissionchangelog.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	return _node, _spec
}

// RbacPermissionChangeLogCreateBulk is the builder for creating many RbacPermissionChangeLog entities in bulk.
type RbacPermissionChangeLogCreateBulk struct {
	config
	err      error
	builders []*RbacPermissionChangeLogCreate
}

// Save creates the RbacPermissionChangeLog entities in the database.
func (_c *RbacPermissionChangeLogCreateBulk) Save(ctx context.Context) ([]*RbacPermissionChangeLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RbacPermissionChangeLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RbacPermissionChangeLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RbacPermissionChangeLogCreateBulk) SaveX(ctx context.Context) []*RbacPermissionChangeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacPermissionChangeLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacPermissionChangeLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
