// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermissionversion"
)

// RbacPermissionVersionUpdate is the builder for updating RbacPermissionVersion entities.
type RbacPermissionVersionUpdate struct {
	config
	hooks    []Hook
	mutation *RbacPermissionVersionMutation
}

// Where appends a list predicates to the RbacPermissionVersionUpdate builder.
func (_u *RbacPermissionVersionUpdate) Where(ps ...predicate.RbacPermissionVersion) *RbacPermissionVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacPermissionVersionUpdate) SetUpdatedAt(v time.Time) *RbacPermissionVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *RbacPermissionVersionUpdate) SetWorkspaceID(v int64) *RbacPermissionVersionUpdate {
	_u.mutation.ResetWorkspaceID()
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdate) SetNillableWorkspaceID(v *int64) *RbacPermissionVersionUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// AddWorkspaceID adds value to the "workspace_id" field.
func (_u *RbacPermissionVersionUpdate) AddWorkspaceID(v int64) *RbacPermissionVersionUpdate {
	_u.mutation.AddWorkspaceID(v)
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *RbacPermissionVersionUpdate) SetSubjectType(v int8) *RbacPermissionVersionUpdate {
	_u.mutation.ResetSubjectType()
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdate) SetNillableSubjectType(v *int8) *RbacPermissionVersionUpdate {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// AddSubjectType adds value to the "subject_type" field.
func (_u *RbacPermissionVersionUpdate) AddSubjectType(v int8) *RbacPermissionVersionUpdate {
	_u.mutation.AddSubjectType(v)
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *RbacPermissionVersionUpdate) SetSubjectID(v int64) *RbacPermissionVersionUpdate {
	_u.mutation.ResetSubjectID()
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdate) SetNillableSubjectID(v *int64) *RbacPermissionVersionUpdate {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// AddSubjectID adds value to the "subject_id" field.
func (_u *RbacPermissionVersionUpdate) AddSubjectID(v int64) *RbacPermissionVersionUpdate {
	_u.mutation.AddSubjectID(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *RbacPermissionVersionUpdate) SetVersion(v int64) *RbacPermissionVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdate) SetNillableVersion(v *int64) *RbacPermissionVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RbacPermissionVersionUpdate) AddVersion(v int64) *RbacPermissionVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the RbacPermissionVersionMutation object of the builder.
func (_u *RbacPermissionVersionUpdate) Mutation() *RbacPermissionVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RbacPermissionVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RbacPermissionVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacPermissionVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacpermissionversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RbacPermissionVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rbacpermissionversion.Table, rbacpermissionversion.Columns, sqlgraph.NewFieldSpec(rbacpermissionversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermissionversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(rbacpermissionversion.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(rbacpermissionversion.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(rbacpermissionversion.FieldSubjectType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedSubjectType(); ok {
		_spec.AddField(rbacpermissionversion.FieldSubjectType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(rbacpermissionversion.FieldSubjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubjectID(); ok {
		_spec.AddField(rbacpermissionversion.FieldSubjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rbacpermissionversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rbacpermissionversion.FieldVersion, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissionversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RbacPermissionVersionUpdateOne is the builder for updating a single RbacPermissionVersion entity.
type RbacPermissionVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RbacPermissionVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacPermissionVersionUpdateOne) SetUpdatedAt(v time.Time) *RbacPermissionVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *RbacPermissionVersionUpdateOne) SetWorkspaceID(v int64) *RbacPermissionVersionUpdateOne {
	_u.mutation.ResetWorkspaceID()
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdateOne) SetNillableWorkspaceID(v *int64) *RbacPermissionVersionUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// AddWorkspaceID adds value to the "workspace_id" field.
func (_u *RbacPermissionVersionUpdateOne) AddWorkspaceID(v int64) *RbacPermissionVersionUpdateOne {
	_u.mutation.AddWorkspaceID(v)
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *RbacPermissionVersionUpdateOne) SetSubjectType(v int8) *RbacPermissionVersionUpdateOne {
	_u.mutation.ResetSubjectType()
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdateOne) SetNillableSubjectType(v *int8) *RbacPermissionVersionUpdateOne {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// AddSubjectType adds value to the "subject_type" field.
func (_u *RbacPermissionVersionUpdateOne) AddSubjectType(v int8) *RbacPermissionVersionUpdateOne {
	_u.mutation.AddSubjectType(v)
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *RbacPermissionVersionUpdateOne) SetSubjectID(v int64) *RbacPermissionVersionUpdateOne {
	_u.mutation.ResetSubjectID()
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdateOne) SetNillableSubjectID(v *int64) *RbacPermissionVersionUpdateOne {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// AddSubjectID adds value to the "subject_id" field.
func (_u *RbacPermissionVersionUpdateOne) AddSubjectID(v int64) *RbacPermissionVersionUpdateOne {
	_u.mutation.AddSubjectID(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *RbacPermissionVersionUpdateOne) SetVersion(v int64) *RbacPermissionVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RbacPermissionVersionUpdateOne) SetNillableVersion(v *int64) *RbacPermissionVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RbacPermissionVersionUpdateOne) AddVersion(v int64) *RbacPermissionVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the RbacPermissionVersionMutation object of the builder.
func (_u *RbacPermissionVersionUpdateOne) Mutation() *RbacPermissionVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RbacPermissionVersionUpdate builder.
func (_u *RbacPermissionVersionUpdateOne) Where(ps ...predicate.RbacPermissionVersion) *RbacPermissionVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RbacPermissionVersionUpdateOne) Select(field string, fields ...string) *RbacPermissionVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RbacPermissionVersion entity.
func (_u *RbacPermissionVersionUpdateOne) Save(ctx context.Context) (*RbacPermissionVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionVersionUpdateOne) SaveX(ctx context.Context) *RbacPermissionVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RbacPermissionVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacPermissionVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacpermissionversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RbacPermissionVersionUpdateOne) sqlSave(ctx context.Context) (_node *RbacPermissionVersion, err error) {
	_spec := sqlgraph.NewUpdateSpec(rbacpermissionversion.Table, rbacpermissionversion.Columns, sqlgraph.NewFieldSpec(rbacpermissionversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RbacPermissionVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacpermissionversion.FieldID)
		for _, f := range fields {
			if !rbacpermissionversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacpermissionversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermissionversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(rbacpermissionversion.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(rbacpermissionversion.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(rbacpermissionversion.FieldSubjectType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedSubjectType(); ok {
		_spec.AddField(rbacpermissionversion.FieldSubjectType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(rbacpermissionversion.FieldSubjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubjectID(); ok {
		_spec.AddField(rbacpermissionversion.FieldSubjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rbacpermissionversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rbacpermissionversion.FieldVersion, field.TypeInt64, value)
	}
	_node = &RbacPermissionVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissionversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
