// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/maguowei/gotobeta/internal/ent/appsetting"
	"github.com/maguowei/gotobeta/internal/ent/authactiontoken"
	"github.com/maguowei/gotobeta/internal/ent/authrefreshtoken"
	"github.com/maguowei/gotobeta/internal/ent/oauthloginstate"
	"github.com/maguowei/gotobeta/internal/ent/rbacaclentry"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermission"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermissionchangelog"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermissionversion"
	"github.com/maguowei/gotobeta/internal/ent/rbacrole"
	"github.com/maguowei/gotobeta/internal/ent/rbacrolepermission"
	"github.com/maguowei/gotobeta/internal/ent/rbacuserrole"
	"github.com/maguowei/gotobeta/internal/ent/schema"
	"github.com/maguowei/gotobeta/internal/ent/todo"
	"github.com/maguowei/gotobeta/internal/ent/user"
	"github.com/maguowei/gotobeta/internal/ent/useridentity"
	"github.com/maguowei/gotobeta/internal/ent/workspace"
	"github.com/maguowei/gotobeta/internal/ent/workspacemember"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appsettingMixin := schema.AppSetting{}.Mixin()
	appsettingMixinFields0 := appsettingMixin[0].Fields()
	_ = appsettingMixinFields0
	appsettingFields := schema.AppSetting{}.Fields()
	_ = appsettingFields
	// appsettingDescCreatedAt is the schema descriptor for created_at field.
	appsettingDescCreatedAt := appsettingMixinFields0[0].Descriptor()
	// appsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	appsetting.DefaultCreatedAt = appsettingDescCreatedAt.Default.(func() time.Time)
	// appsettingDescUpdatedAt is the schema descriptor for updated_at field.
	appsettingDescUpdatedAt := appsettingMixinFields0[1].Descriptor()
	// appsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appsetting.DefaultUpdatedAt = appsettingDescUpdatedAt.Default.(func() time.Time)
	// appsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appsetting.UpdateDefaultUpdatedAt = appsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appsettingDescValue is the schema descriptor for value field.
	appsettingDescValue := appsettingFields[1].Descriptor()
	// appsetting.DefaultValue holds the default value on creation for the value field.
	appsetting.DefaultValue = appsettingDescValue.Default.(string)
	authactiontokenMixin := schema.AuthActionToken{}.Mixin()
	authactiontokenMixinFields0 := authactiontokenMixin[0].Fields()
	_ = authactiontokenMixinFields0
	authactiontokenFields := schema.AuthActionToken{}.Fields()
	_ = authactiontokenFields
	// authactiontokenDescCreatedAt is the schema descriptor for created_at field.
	authactiontokenDescCreatedAt := authactiontokenMixinFields0[0].Descriptor()
	// authactiontoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	authactiontoken.DefaultCreatedAt = authactiontokenDescCreatedAt.Default.(func() time.Time)
	// authactiontokenDescUpdatedAt is the schema descriptor for updated_at field.
	authactiontokenDescUpdatedAt := authactiontokenMixinFields0[1].Descriptor()
	// authactiontoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authactiontoken.DefaultUpdatedAt = authactiontokenDescUpdatedAt.Default.(func() time.Time)
	// authactiontoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authactiontoken.UpdateDefaultUpdatedAt = authactiontokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authactiontokenDescTokenID is the schema descriptor for token_id field.
	authactiontokenDescTokenID := authactiontokenFields[0].Descriptor()
	// authactiontoken.TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	authactiontoken.TokenIDValidator = authactiontokenDescTokenID.Validators[0].(func(string) error)
	// authactiontokenDescPurpose is the schema descriptor for purpose field.
	authactiontokenDescPurpose := authactiontokenFields[2].Descriptor()
	// authactiontoken.PurposeValidator is a validator for the "purpose" field. It is called by the builders before save.
	authactiontoken.PurposeValidator = authactiontokenDescPurpose.Validators[0].(func(string) error)
	// authactiontokenDescTokenHash is the schema descriptor for token_hash field.
	authactiontokenDescTokenHash := authactiontokenFields[3].Descriptor()
	// authactiontoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	authactiontoken.TokenHashValidator = authactiontokenDescTokenHash.Validators[0].(func(string) error)
	// authactiontokenDescTargetEmailNormalized is the schema descriptor for target_email_normalized field.
	authactiontokenDescTargetEmailNormalized := authactiontokenFields[4].Descriptor()
	// authactiontoken.DefaultTargetEmailNormalized holds the default value on creation for the target_email_normalized field.
	authactiontoken.DefaultTargetEmailNormalized = authactiontokenDescTargetEmailNormalized.Default.(string)
	// authactiontoken.TargetEmailNormalizedValidator is a validator for the "target_email_normalized" field. It is called by the builders before save.
	authactiontoken.TargetEmailNormalizedValidator = authactiontokenDescTargetEmailNormalized.Validators[0].(func(string) error)
	authrefreshtokenMixin := schema.AuthRefreshToken{}.Mixin()
	authrefreshtokenMixinFields0 := authrefreshtokenMixin[0].Fields()
	_ = authrefreshtokenMixinFields0
	authrefreshtokenFields := schema.AuthRefreshToken{}.Fields()
	_ = authrefreshtokenFields
	// authrefreshtokenDescCreatedAt is the schema descriptor for created_at field.
	authrefreshtokenDescCreatedAt := authrefreshtokenMixinFields0[0].Descriptor()
	// authrefreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	authrefreshtoken.DefaultCreatedAt = authrefreshtokenDescCreatedAt.Default.(func() time.Time)
	// authrefreshtokenDescUpdatedAt is the schema descriptor for updated_at field.
	authrefreshtokenDescUpdatedAt := authrefreshtokenMixinFields0[1].Descriptor()
	// authrefreshtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authrefreshtoken.DefaultUpdatedAt = authrefreshtokenDescUpdatedAt.Default.(func() time.Time)
	// authrefreshtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authrefreshtoken.UpdateDefaultUpdatedAt = authrefreshtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authrefreshtokenDescTokenID is the schema descriptor for token_id field.
	authrefreshtokenDescTokenID := authrefreshtokenFields[0].Descriptor()
	// authrefreshtoken.TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	authrefreshtoken.TokenIDValidator = authrefreshtokenDescTokenID.Validators[0].(func(string) error)
	// authrefreshtokenDescTokenHash is the schema descriptor for token_hash field.
	authrefreshtokenDescTokenHash := authrefreshtokenFields[2].Descriptor()
	// authrefreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	authrefreshtoken.TokenHashValidator = authrefreshtokenDescTokenHash.Validators[0].(func(string) error)
	// authrefreshtokenDescReplacedByTokenID is the schema descriptor for replaced_by_token_id field.
	authrefreshtokenDescReplacedByTokenID := authrefreshtokenFields[3].Descriptor()
	// authrefreshtoken.ReplacedByTokenIDValidator is a validator for the "replaced_by_token_id" field. It is called by the builders before save.
	authrefreshtoken.ReplacedByTokenIDValidator = authrefreshtokenDescReplacedByTokenID.Validators[0].(func(string) error)
	// authrefreshtokenDescRevokeReason is the schema descriptor for revoke_reason field.
	authrefreshtokenDescRevokeReason := authrefreshtokenFields[6].Descriptor()
	// authrefreshtoken.DefaultRevokeReason holds the default value on creation for the revoke_reason field.
	authrefreshtoken.DefaultRevokeReason = authrefreshtokenDescRevokeReason.Default.(string)
	// authrefreshtoken.RevokeReasonValidator is a validator for the "revoke_reason" field. It is called by the builders before save.
	authrefreshtoken.RevokeReasonValidator = authrefreshtokenDescRevokeReason.Validators[0].(func(string) error)
	oauthloginstateMixin := schema.OAuthLoginState{}.Mixin()
	oauthloginstateMixinFields0 := oauthloginstateMixin[0].Fields()
	_ = oauthloginstateMixinFields0
	oauthloginstateFields := schema.OAuthLoginState{}.Fields()
	_ = oauthloginstateFields
	// oauthloginstateDescCreatedAt is the schema descriptor for created_at field.
	oauthloginstateDescCreatedAt := oauthloginstateMixinFields0[0].Descriptor()
	// oauthloginstate.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthloginstate.DefaultCreatedAt = oauthloginstateDescCreatedAt.Default.(func() time.Time)
	// oauthloginstateDescUpdatedAt is the schema descriptor for updated_at field.
	oauthloginstateDescUpdatedAt := oauthloginstateMixinFields0[1].Descriptor()
	// oauthloginstate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthloginstate.DefaultUpdatedAt = oauthloginstateDescUpdatedAt.Default.(func() time.Time)
	// oauthloginstate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthloginstate.UpdateDefaultUpdatedAt = oauthloginstateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthloginstateDescStateHash is the schema descriptor for state_hash field.
	oauthloginstateDescStateHash := oauthloginstateFields[0].Descriptor()
	// oauthloginstate.StateHashValidator is a validator for the "state_hash" field. It is called by the builders before save.
	oauthloginstate.StateHashValidator = oauthloginstateDescStateHash.Validators[0].(func(string) error)
	// oauthloginstateDescProvider is the schema descriptor for provider field.
	oauthloginstateDescProvider := oauthloginstateFields[1].Descriptor()
	// oauthloginstate.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	oauthloginstate.ProviderValidator = oauthloginstateDescProvider.Validators[0].(func(string) error)
	// oauthloginstateDescRedirectURL is the schema descriptor for redirect_url field.
	oauthloginstateDescRedirectURL := oauthloginstateFields[2].Descriptor()
	// oauthloginstate.RedirectURLValidator is a validator for the "redirect_url" field. It is called by the builders before save.
	oauthloginstate.RedirectURLValidator = oauthloginstateDescRedirectURL.Validators[0].(func(string) error)
	rbacaclentryMixin := schema.RbacAclEntry{}.Mixin()
	rbacaclentryMixinFields0 := rbacaclentryMixin[0].Fields()
	_ = rbacaclentryMixinFields0
	rbacaclentryFields := schema.RbacAclEntry{}.Fields()
	_ = rbacaclentryFields
	// rbacaclentryDescCreatedAt is the schema descriptor for created_at field.
	rbacaclentryDescCreatedAt := rbacaclentryMixinFields0[0].Descriptor()
	// rbacaclentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacaclentry.DefaultCreatedAt = rbacaclentryDescCreatedAt.Default.(func() time.Time)
	// rbacaclentryDescUpdatedAt is the schema descriptor for updated_at field.
	rbacaclentryDescUpdatedAt := rbacaclentryMixinFields0[1].Descriptor()
	// rbacaclentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacaclentry.DefaultUpdatedAt = rbacaclentryDescUpdatedAt.Default.(func() time.Time)
	// rbacaclentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacaclentry.UpdateDefaultUpdatedAt = rbacaclentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rbacaclentryDescResourceType is the schema descriptor for resource_type field.
	rbacaclentryDescResourceType := rbacaclentryFields[4].Descriptor()
	// rbacaclentry.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	rbacaclentry.ResourceTypeValidator = rbacaclentryDescResourceType.Validators[0].(func(string) error)
	// rbacaclentryDescResourceID is the schema descriptor for resource_id field.
	rbacaclentryDescResourceID := rbacaclentryFields[5].Descriptor()
	// rbacaclentry.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	rbacaclentry.ResourceIDValidator = rbacaclentryDescResourceID.Validators[0].(func(string) error)
	// rbacaclentryDescActionCode is the schema descriptor for action_code field.
	rbacaclentryDescActionCode := rbacaclentryFields[6].Descriptor()
	// rbacaclentry.ActionCodeValidator is a validator for the "action_code" field. It is called by the builders before save.
	rbacaclentry.ActionCodeValidator = rbacaclentryDescActionCode.Validators[0].(func(string) error)
	// rbacaclentryDescReason is the schema descriptor for reason field.
	rbacaclentryDescReason := rbacaclentryFields[8].Descriptor()
	// rbacaclentry.DefaultReason holds the default value on creation for the reason field.
	rbacaclentry.DefaultReason = rbacaclentryDescReason.Default.(string)
	// rbacaclentry.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	rbacaclentry.ReasonValidator = rbacaclentryDescReason.Validators[0].(func(string) error)
	// rbacaclentryDescSourceType is the schema descriptor for source_type field.
	rbacaclentryDescSourceType := rbacaclentryFields[9].Descriptor()
	// rbacaclentry.DefaultSourceType holds the default value on creation for the source_type field.
	rbacaclentry.DefaultSourceType = rbacaclentryDescSourceType.Default.(int8)
	// rbacaclentryDescCreatedBy is the schema descriptor for created_by field.
	rbacaclentryDescCreatedBy := rbacaclentryFields[11].Descriptor()
	// rbacaclentry.DefaultCreatedBy holds the default value on creation for the created_by field.
	rbacaclentry.DefaultCreatedBy = rbacaclentryDescCreatedBy.Default.(int64)
	rbacpermissionMixin := schema.RbacPermission{}.Mixin()
	rbacpermissionMixinFields0 := rbacpermissionMixin[0].Fields()
	_ = rbacpermissionMixinFields0
	rbacpermissionFields := schema.RbacPermission{}.Fields()
	_ = rbacpermissionFields
	// rbacpermissionDescCreatedAt is the schema descriptor for created_at field.
	rbacpermissionDescCreatedAt := rbacpermissionMixinFields0[0].Descriptor()
	// rbacpermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacpermission.DefaultCreatedAt = rbacpermissionDescCreatedAt.Default.(func() time.Time)
	// rbacpermissionDescUpdatedAt is the schema descriptor for updated_at field.
	rbacpermissionDescUpdatedAt := rbacpermissionMixinFields0[1].Descriptor()
	// rbacpermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacpermission.DefaultUpdatedAt = rbacpermissionDescUpdatedAt.Default.(func() time.Time)
	// rbacpermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacpermission.UpdateDefaultUpdatedAt = rbacpermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rbacpermissionDescWorkspaceID is the schema descriptor for workspace_id field.
	rbacpermissionDescWorkspaceID := rbacpermissionFields[1].Descriptor()
	// rbacpermission.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	rbacpermission.DefaultWorkspaceID = rbacpermissionDescWorkspaceID.Default.(int64)
	// rbacpermissionDescCode is the schema descriptor for code field.
	rbacpermissionDescCode := rbacpermissionFields[2].Descriptor()
	// rbacpermission.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	rbacpermission.CodeValidator = rbacpermissionDescCode.Validators[0].(func(string) error)
	// rbacpermissionDescName is the schema descriptor for name field.
	rbacpermissionDescName := rbacpermissionFields[3].Descriptor()
	// rbacpermission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	rbacpermission.NameValidator = rbacpermissionDescName.Validators[0].(func(string) error)
	// rbacpermissionDescResourceType is the schema descriptor for resource_type field.
	rbacpermissionDescResourceType := rbacpermissionFields[4].Descriptor()
	// rbacpermission.DefaultResourceType holds the default value on creation for the resource_type field.
	rbacpermission.DefaultResourceType = rbacpermissionDescResourceType.Default.(string)
	// rbacpermission.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	rbacpermission.ResourceTypeValidator = rbacpermissionDescResourceType.Validators[0].(func(string) error)
	// rbacpermissionDescActionKey is the schema descriptor for action_key field.
	rbacpermissionDescActionKey := rbacpermissionFields[5].Descriptor()
	// rbacpermission.DefaultActionKey holds the default value on creation for the action_key field.
	rbacpermission.DefaultActionKey = rbacpermissionDescActionKey.Default.(string)
	// rbacpermission.ActionKeyValidator is a validator for the "action_key" field. It is called by the builders before save.
	rbacpermission.ActionKeyValidator = rbacpermissionDescActionKey.Validators[0].(func(string) error)
	// rbacpermissionDescStatus is the schema descriptor for status field.
	rbacpermissionDescStatus := rbacpermissionFields[6].Descriptor()
	// rbacpermission.DefaultStatus holds the default value on creation for the status field.
	rbacpermission.DefaultStatus = rbacpermissionDescStatus.Default.(int8)
	rbacpermissionchangelogMixin := schema.RbacPermissionChangeLog{}.Mixin()
	rbacpermissionchangelogMixinFields0 := rbacpermissionchangelogMixin[0].Fields()
	_ = rbacpermissionchangelogMixinFields0
	rbacpermissionchangelogFields := schema.RbacPermissionChangeLog{}.Fields()
	_ = rbacpermissionchangelogFields
	// rbacpermissionchangelogDescCreatedAt is the schema descriptor for created_at field.
	rbacpermissionchangelogDescCreatedAt := rbacpermissionchangelogMixinFields0[0].Descriptor()
	// rbacpermissionchangelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacpermissionchangelog.DefaultCreatedAt = rbacpermissionchangelogDescCreatedAt.Default.(func() time.Time)
	// rbacpermissionchangelogDescUpdatedAt is the schema descriptor for updated_at field.
	rbacpermissionchangelogDescUpdatedAt := rbacpermissionchangelogMixinFields0[1].Descriptor()
	// rbacpermissionchangelog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacpermissionchangelog.DefaultUpdatedAt = rbacpermissionchangelogDescUpdatedAt.Default.(func() time.Time)
	// rbacpermissionchangelog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacpermissionchangelog.UpdateDefaultUpdatedAt = rbacpermissionchangelogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rbacpermissionchangelogDescTargetID is the schema descriptor for target_id field.
	rbacpermissionchangelogDescTargetID := rbacpermissionchangelogFields[4].Descriptor()
	// rbacpermissionchangelog.DefaultTargetID holds the default value on creation for the target_id field.
	rbacpermissionchangelog.DefaultTargetID = rbacpermissionchangelogDescTargetID.Default.(int64)
	// rbacpermissionchangelogDescOperatorID is the schema descriptor for operator_id field.
	rbacpermissionchangelogDescOperatorID := rbacpermissionchangelogFields[5].Descriptor()
	// rbacpermissionchangelog.DefaultOperatorID holds the default value on creation for the operator_id field.
	rbacpermissionchangelog.DefaultOperatorID = rbacpermissionchangelogDescOperatorID.Default.(int64)
	// rbacpermissionchangelogDescRequestID is the schema descriptor for request_id field.
	rbacpermissionchangelogDescRequestID := rbacpermissionchangelogFields[6].Descriptor()
	// rbacpermissionchangelog.DefaultRequestID holds the default value on creation for the request_id field.
	rbacpermissionchangelog.DefaultRequestID = rbacpermissionchangelogDescRequestID.Default.(string)
	// rbacpermissionchangelog.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	rbacpermissionchangelog.RequestIDValidator = rbacpermissionchangelogDescRequestID.Validators[0].(func(string) error)
	// rbacpermissionchangelogDescReason is the schema descriptor for reason field.
	rbacpermissionchangelogDescReason := rbacpermissionchangelogFields[9].Descriptor()
	// rbacpermissionchangelog.DefaultReason holds the default value on creation for the reason field.
	rbacpermissionchangelog.DefaultReason = rbacpermissionchangelogDescReason.Default.(string)
	// rbacpermissionchangelog.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	rbacpermissionchangelog.ReasonValidator = rbacpermissionchangelogDescReason.Validators[0].(func(string) error)
	rbacpermissionversionMixin := schema.RbacPermissionVersion{}.Mixin()
	rbacpermissionversionMixinFields0 := rbacpermissionversionMixin[0].Fields()
	_ = rbacpermissionversionMixinFields0
	rbacpermissionversionFields := schema.RbacPermissionVersion{}.Fields()
	_ = rbacpermissionversionFields
	// rbacpermissionversionDescCreatedAt is the schema descriptor for created_at field.
	rbacpermissionversionDescCreatedAt := rbacpermissionversionMixinFields0[0].Descriptor()
	// rbacpermissionversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacpermissionversion.DefaultCreatedAt = rbacpermissionversionDescCreatedAt.Default.(func() time.Time)
	// rbacpermissionversionDescUpdatedAt is the schema descriptor for updated_at field.
	rbacpermissionversionDescUpdatedAt := rbacpermissionversionMixinFields0[1].Descriptor()
	// rbacpermissionversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacpermissionversion.DefaultUpdatedAt = rbacpermissionversionDescUpdatedAt.Default.(func() time.Time)
	// rbacpermissionversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacpermissionversion.UpdateDefaultUpdatedAt = rbacpermissionversionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rbacpermissionversionDescVersion is the schema descriptor for version field.
	rbacpermissionversionDescVersion := rbacpermissionversionFields[3].Descriptor()
	// rbacpermissionversion.DefaultVersion holds the default value on creation for the version field.
	rbacpermissionversion.DefaultVersion = rbacpermissionversionDescVersion.Default.(int64)
	rbacroleMixin := schema.RbacRole{}.Mixin()
	rbacroleMixinFields0 := rbacroleMixin[0].Fields()
	_ = rbacroleMixinFields0
	rbacroleFields := schema.RbacRole{}.Fields()
	_ = rbacroleFields
	// rbacroleDescCreatedAt is the schema descriptor for created_at field.
	rbacroleDescCreatedAt := rbacroleMixinFields0[0].Descriptor()
	// rbacrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacrole.DefaultCreatedAt = rbacroleDescCreatedAt.Default.(func() time.Time)
	// rbacroleDescUpdatedAt is the schema descriptor for updated_at field.
	rbacroleDescUpdatedAt := rbacroleMixinFields0[1].Descriptor()
	// rbacrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacrole.DefaultUpdatedAt = rbacroleDescUpdatedAt.Default.(func() time.Time)
	// rbacrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacrole.UpdateDefaultUpdatedAt = rbacroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rbacroleDescWorkspaceID is the schema descriptor for workspace_id field.
	rbacroleDescWorkspaceID := rbacroleFields[1].Descriptor()
	// rbacrole.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	rbacrole.DefaultWorkspaceID = rbacroleDescWorkspaceID.Default.(int64)
	// rbacroleDescCode is the schema descriptor for code field.
	rbacroleDescCode := rbacroleFields[2].Descriptor()
	// rbacrole.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	rbacrole.CodeValidator = rbacroleDescCode.Validators[0].(func(string) error)
	// rbacroleDescName is the schema descriptor for name field.
	rbacroleDescName := rbacroleFields[3].Descriptor()
	// rbacrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	rbacrole.NameValidator = rbacroleDescName.Validators[0].(func(string) error)
	// rbacroleDescRoleType is the schema descriptor for role_type field.
	rbacroleDescRoleType := rbacroleFields[4].Descriptor()
	// rbacrole.DefaultRoleType holds the default value on creation for the role_type field.
	rbacrole.DefaultRoleType = rbacroleDescRoleType.Default.(int8)
	// rbacroleDescStatus is the schema descriptor for status field.
	rbacroleDescStatus := rbacroleFields[5].Descriptor()
	// rbacrole.DefaultStatus holds the default value on creation for the status field.
	rbacrole.DefaultStatus = rbacroleDescStatus.Default.(int8)
	rbacrolepermissionMixin := schema.RbacRolePermission{}.Mixin()
	rbacrolepermissionMixinFields0 := rbacrolepermissionMixin[0].Fields()
	_ = rbacrolepermissionMixinFields0
	rbacrolepermissionFields := schema.RbacRolePermission{}.Fields()
	_ = rbacrolepermissionFields
	// rbacrolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rbacrolepermissionDescCreatedAt := rbacrolepermissionMixinFields0[0].Descriptor()
	// rbacrolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacrolepermission.DefaultCreatedAt = rbacrolepermissionDescCreatedAt.Default.(func() time.Time)
	// rbacrolepermissionDescUpdatedAt is the schema descriptor for updated_at field.
	rbacrolepermissionDescUpdatedAt := rbacrolepermissionMixinFields0[1].Descriptor()
	// rbacrolepermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacrolepermission.DefaultUpdatedAt = rbacrolepermissionDescUpdatedAt.Default.(func() time.Time)
	// rbacrolepermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacrolepermission.UpdateDefaultUpdatedAt = rbacrolepermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rbacrolepermissionDescWorkspaceID is the schema descriptor for workspace_id field.
	rbacrolepermissionDescWorkspaceID := rbacrolepermissionFields[0].Descriptor()
	// rbacrolepermission.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	rbacrolepermission.DefaultWorkspaceID = rbacrolepermissionDescWorkspaceID.Default.(int64)
	rbacuserroleMixin := schema.RbacUserRole{}.Mixin()
	rbacuserroleMixinFields0 := rbacuserroleMixin[0].Fields()
	_ = rbacuserroleMixinFields0
	rbacuserroleFields := schema.RbacUserRole{}.Fields()
	_ = rbacuserroleFields
	// rbacuserroleDescCreatedAt is the schema descriptor for created_at field.
	rbacuserroleDescCreatedAt := rbacuserroleMixinFields0[0].Descriptor()
	// rbacuserrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacuserrole.DefaultCreatedAt = rbacuserroleDescCreatedAt.Default.(func() time.Time)
	// rbacuserroleDescUpdatedAt is the schema descriptor for updated_at field.
	rbacuserroleDescUpdatedAt := rbacuserroleMixinFields0[1].Descriptor()
	// rbacuserrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacuserrole.DefaultUpdatedAt = rbacuserroleDescUpdatedAt.Default.(func() time.Time)
	// rbacuserrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacuserrole.UpdateDefaultUpdatedAt = rbacuserroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rbacuserroleDescSourceType is the schema descriptor for source_type field.
	rbacuserroleDescSourceType := rbacuserroleFields[3].Descriptor()
	// rbacuserrole.DefaultSourceType holds the default value on creation for the source_type field.
	rbacuserrole.DefaultSourceType = rbacuserroleDescSourceType.Default.(int8)
	todoMixin := schema.Todo{}.Mixin()
	todoMixinFields0 := todoMixin[0].Fields()
	_ = todoMixinFields0
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoMixinFields0[0].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(func() time.Time)
	// todoDescUpdatedAt is the schema descriptor for updated_at field.
	todoDescUpdatedAt := todoMixinFields0[1].Descriptor()
	// todo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todo.DefaultUpdatedAt = todoDescUpdatedAt.Default.(func() time.Time)
	// todo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	todo.UpdateDefaultUpdatedAt = todoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// todoDescStatus is the schema descriptor for status field.
	todoDescStatus := todoFields[2].Descriptor()
	// todo.DefaultStatus holds the default value on creation for the status field.
	todo.DefaultStatus = todoDescStatus.Default.(string)
	// todoDescVersion is the schema descriptor for version field.
	todoDescVersion := todoFields[3].Descriptor()
	// todo.DefaultVersion holds the default value on creation for the version field.
	todo.DefaultVersion = todoDescVersion.Default.(int)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescEmailNormalized is the schema descriptor for email_normalized field.
	userDescEmailNormalized := userFields[2].Descriptor()
	// user.EmailNormalizedValidator is a validator for the "email_normalized" field. It is called by the builders before save.
	user.EmailNormalizedValidator = userDescEmailNormalized.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[4].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescPasswordHashAlg is the schema descriptor for password_hash_alg field.
	userDescPasswordHashAlg := userFields[5].Descriptor()
	// user.PasswordHashAlgValidator is a validator for the "password_hash_alg" field. It is called by the builders before save.
	user.PasswordHashAlgValidator = userDescPasswordHashAlg.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[7].Descriptor()
	// user.DefaultDisplayName holds the default value on creation for the display_name field.
	user.DefaultDisplayName = userDescDisplayName.Default.(string)
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[8].Descriptor()
	// user.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	user.DefaultAvatarURL = userDescAvatarURL.Default.(string)
	// user.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	user.AvatarURLValidator = userDescAvatarURL.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[9].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	useridentityMixin := schema.UserIdentity{}.Mixin()
	useridentityMixinFields0 := useridentityMixin[0].Fields()
	_ = useridentityMixinFields0
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescCreatedAt is the schema descriptor for created_at field.
	useridentityDescCreatedAt := useridentityMixinFields0[0].Descriptor()
	// useridentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	useridentity.DefaultCreatedAt = useridentityDescCreatedAt.Default.(func() time.Time)
	// useridentityDescUpdatedAt is the schema descriptor for updated_at field.
	useridentityDescUpdatedAt := useridentityMixinFields0[1].Descriptor()
	// useridentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useridentity.DefaultUpdatedAt = useridentityDescUpdatedAt.Default.(func() time.Time)
	// useridentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useridentity.UpdateDefaultUpdatedAt = useridentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// useridentityDescProvider is the schema descriptor for provider field.
	useridentityDescProvider := useridentityFields[2].Descriptor()
	// useridentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	useridentity.ProviderValidator = useridentityDescProvider.Validators[0].(func(string) error)
	// useridentityDescProviderUserID is the schema descriptor for provider_user_id field.
	useridentityDescProviderUserID := useridentityFields[3].Descriptor()
	// useridentity.ProviderUserIDValidator is a validator for the "provider_user_id" field. It is called by the builders before save.
	useridentity.ProviderUserIDValidator = useridentityDescProviderUserID.Validators[0].(func(string) error)
	// useridentityDescProviderEmail is the schema descriptor for provider_email field.
	useridentityDescProviderEmail := useridentityFields[4].Descriptor()
	// useridentity.DefaultProviderEmail holds the default value on creation for the provider_email field.
	useridentity.DefaultProviderEmail = useridentityDescProviderEmail.Default.(string)
	// useridentity.ProviderEmailValidator is a validator for the "provider_email" field. It is called by the builders before save.
	useridentity.ProviderEmailValidator = useridentityDescProviderEmail.Validators[0].(func(string) error)
	// useridentityDescProviderEmailNormalized is the schema descriptor for provider_email_normalized field.
	useridentityDescProviderEmailNormalized := useridentityFields[5].Descriptor()
	// useridentity.DefaultProviderEmailNormalized holds the default value on creation for the provider_email_normalized field.
	useridentity.DefaultProviderEmailNormalized = useridentityDescProviderEmailNormalized.Default.(string)
	// useridentity.ProviderEmailNormalizedValidator is a validator for the "provider_email_normalized" field. It is called by the builders before save.
	useridentity.ProviderEmailNormalizedValidator = useridentityDescProviderEmailNormalized.Validators[0].(func(string) error)
	// useridentityDescProviderEmailVerified is the schema descriptor for provider_email_verified field.
	useridentityDescProviderEmailVerified := useridentityFields[6].Descriptor()
	// useridentity.DefaultProviderEmailVerified holds the default value on creation for the provider_email_verified field.
	useridentity.DefaultProviderEmailVerified = useridentityDescProviderEmailVerified.Default.(bool)
	// useridentityDescDisplayName is the schema descriptor for display_name field.
	useridentityDescDisplayName := useridentityFields[7].Descriptor()
	// useridentity.DefaultDisplayName holds the default value on creation for the display_name field.
	useridentity.DefaultDisplayName = useridentityDescDisplayName.Default.(string)
	// useridentity.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	useridentity.DisplayNameValidator = useridentityDescDisplayName.Validators[0].(func(string) error)
	// useridentityDescAvatarURL is the schema descriptor for avatar_url field.
	useridentityDescAvatarURL := useridentityFields[8].Descriptor()
	// useridentity.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	useridentity.DefaultAvatarURL = useridentityDescAvatarURL.Default.(string)
	// useridentity.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	useridentity.AvatarURLValidator = useridentityDescAvatarURL.Validators[0].(func(string) error)
	// useridentityDescProfileURL is the schema descriptor for profile_url field.
	useridentityDescProfileURL := useridentityFields[9].Descriptor()
	// useridentity.DefaultProfileURL holds the default value on creation for the profile_url field.
	useridentity.DefaultProfileURL = useridentityDescProfileURL.Default.(string)
	// useridentity.ProfileURLValidator is a validator for the "profile_url" field. It is called by the builders before save.
	useridentity.ProfileURLValidator = useridentityDescProfileURL.Validators[0].(func(string) error)
	workspaceMixin := schema.Workspace{}.Mixin()
	workspaceMixinFields0 := workspaceMixin[0].Fields()
	_ = workspaceMixinFields0
	workspaceFields := schema.Workspace{}.Fields()
	_ = workspaceFields
	// workspaceDescCreatedAt is the schema descriptor for created_at field.
	workspaceDescCreatedAt := workspaceMixinFields0[0].Descriptor()
	// workspace.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspace.DefaultCreatedAt = workspaceDescCreatedAt.Default.(func() time.Time)
	// workspaceDescUpdatedAt is the schema descriptor for updated_at field.
	workspaceDescUpdatedAt := workspaceMixinFields0[1].Descriptor()
	// workspace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspace.DefaultUpdatedAt = workspaceDescUpdatedAt.Default.(func() time.Time)
	// workspace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspace.UpdateDefaultUpdatedAt = workspaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspaceDescSlug is the schema descriptor for slug field.
	workspaceDescSlug := workspaceFields[1].Descriptor()
	// workspace.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	workspace.SlugValidator = workspaceDescSlug.Validators[0].(func(string) error)
	// workspaceDescName is the schema descriptor for name field.
	workspaceDescName := workspaceFields[2].Descriptor()
	// workspace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workspace.NameValidator = workspaceDescName.Validators[0].(func(string) error)
	// workspaceDescStatus is the schema descriptor for status field.
	workspaceDescStatus := workspaceFields[4].Descriptor()
	// workspace.DefaultStatus holds the default value on creation for the status field.
	workspace.DefaultStatus = workspaceDescStatus.Default.(int8)
	workspacememberMixin := schema.WorkspaceMember{}.Mixin()
	workspacememberMixinFields0 := workspacememberMixin[0].Fields()
	_ = workspacememberMixinFields0
	workspacememberFields := schema.WorkspaceMember{}.Fields()
	_ = workspacememberFields
	// workspacememberDescCreatedAt is the schema descriptor for created_at field.
	workspacememberDescCreatedAt := workspacememberMixinFields0[0].Descriptor()
	// workspacemember.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspacemember.DefaultCreatedAt = workspacememberDescCreatedAt.Default.(func() time.Time)
	// workspacememberDescUpdatedAt is the schema descriptor for updated_at field.
	workspacememberDescUpdatedAt := workspacememberMixinFields0[1].Descriptor()
	// workspacemember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspacemember.DefaultUpdatedAt = workspacememberDescUpdatedAt.Default.(func() time.Time)
	// workspacemember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspacemember.UpdateDefaultUpdatedAt = workspacememberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspacememberDescStatus is the schema descriptor for status field.
	workspacememberDescStatus := workspacememberFields[3].Descriptor()
	// workspacemember.DefaultStatus holds the default value on creation for the status field.
	workspacemember.DefaultStatus = workspacememberDescStatus.Default.(int8)
	// workspacememberDescJoinedAt is the schema descriptor for joined_at field.
	workspacememberDescJoinedAt := workspacememberFields[4].Descriptor()
	// workspacemember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	workspacemember.DefaultJoinedAt = workspacememberDescJoinedAt.Default.(func() time.Time)
}
