// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maguowei/gotobeta/internal/ent/workspace"
)

// WorkspaceCreate is the builder for creating a Workspace entity.
type WorkspaceCreate struct {
	config
	mutation *WorkspaceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceCreate) SetCreatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceCreate) SetUpdatedAt(v time.Time) *WorkspaceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBizID sets the "biz_id" field.
func (_c *WorkspaceCreate) SetBizID(v int64) *WorkspaceCreate {
	_c.mutation.SetBizID(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *WorkspaceCreate) SetSlug(v string) *WorkspaceCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *WorkspaceCreate) SetName(v string) *WorkspaceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *WorkspaceCreate) SetOwnerUserID(v int64) *WorkspaceCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WorkspaceCreate) SetStatus(v int8) *WorkspaceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WorkspaceCreate) SetNillableStatus(v *int8) *WorkspaceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettings sets the "settings" field.
func (_c *WorkspaceCreate) SetSettings(v map[string]interface{}) *WorkspaceCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_c *WorkspaceCreate) Mutation() *WorkspaceMutation {
	return _c.mutation
}

// Save creates the Workspace in the database.
func (_c *WorkspaceCreate) Save(ctx context.Context) (*Workspace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceCreate) SaveX(ctx context.Context) *Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspace.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workspace.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := workspace.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Workspace.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Workspace.updated_at"`)}
	}
	if _, ok := _c.mutation.BizID(); !ok {
		return &ValidationError{Name: "biz_id", err: errors.New(`ent: missing required field "Workspace.biz_id"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Workspace.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := workspace.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Workspace.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Workspace.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Workspace.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Workspace.status"`)}
	}
	return nil
}

func (_c *WorkspaceCreate) sqlSave(ctx context.Context) (*Workspace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceCreate) createSpec() (*Workspace, *sqlgraph.CreateSpec) {
	var (
		_node = &Workspace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspace.Table, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.BizID(); ok {
		_spec.SetField(workspace.FieldBizID, field.TypeInt64, value)
		_node.BizID = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(workspace.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(workspace.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(workspace.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	return _node, _spec
}

// WorkspaceCreateBulk is the builder for creating many Workspace entities in bulk.
type WorkspaceCreateBulk struct {
	config
	err      error
	builders []*WorkspaceCreate
}

// Save creates the Workspace entities in the database.
func (_c *WorkspaceCreateBulk) Save(ctx context.Context) ([]*Workspace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Workspace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) SaveX(ctx context.Context) []*Workspace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
