// Code generated by ent, DO NOT EDIT.

package authrefreshtoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the authrefreshtoken type in the database.
	Label = "auth_refresh_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTokenID holds the string denoting the token_id field in the database.
	FieldTokenID = "token_id"
	// FieldUserBizID holds the string denoting the user_biz_id field in the database.
	FieldUserBizID = "user_biz_id"
	// FieldTokenHash holds the string denoting the token_hash field in the database.
	FieldTokenHash = "token_hash"
	// FieldReplacedByTokenID holds the string denoting the replaced_by_token_id field in the database.
	FieldReplacedByTokenID = "replaced_by_token_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldRevokeReason holds the string denoting the revoke_reason field in the database.
	FieldRevokeReason = "revoke_reason"
	// Table holds the table name of the authrefreshtoken in the database.
	Table = "auth_refresh_tokens"
)

// Columns holds all SQL columns for authrefreshtoken fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTokenID,
	FieldUserBizID,
	FieldTokenHash,
	FieldReplacedByTokenID,
	FieldExpiresAt,
	FieldRevokedAt,
	FieldRevokeReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	TokenIDValidator func(string) error
	// TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	TokenHashValidator func(string) error
	// ReplacedByTokenIDValidator is a validator for the "replaced_by_token_id" field. It is called by the builders before save.
	ReplacedByTokenIDValidator func(string) error
	// DefaultRevokeReason holds the default value on creation for the "revoke_reason" field.
	DefaultRevokeReason string
	// RevokeReasonValidator is a validator for the "revoke_reason" field. It is called by the builders before save.
	RevokeReasonValidator func(string) error
)

// OrderOption defines the ordering options for the AuthRefreshToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTokenID orders the results by the token_id field.
func ByTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenID, opts...).ToFunc()
}

// ByUserBizID orders the results by the user_biz_id field.
func ByUserBizID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserBizID, opts...).ToFunc()
}

// ByTokenHash orders the results by the token_hash field.
func ByTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenHash, opts...).ToFunc()
}

// ByReplacedByTokenID orders the results by the replaced_by_token_id field.
func ByReplacedByTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplacedByTokenID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByRevokeReason orders the results by the revoke_reason field.
func ByRevokeReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokeReason, opts...).ToFunc()
}
