// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/maguowei/gotobeta/internal/ent"
	"github.com/maguowei/gotobeta/internal/ent/appsetting"
	"github.com/maguowei/gotobeta/internal/ent/attachment"
	"github.com/maguowei/gotobeta/internal/ent/authactiontoken"
	"github.com/maguowei/gotobeta/internal/ent/authrefreshtoken"
	"github.com/maguowei/gotobeta/internal/ent/bot"
	"github.com/maguowei/gotobeta/internal/ent/conversation"
	"github.com/maguowei/gotobeta/internal/ent/conversationmember"
	"github.com/maguowei/gotobeta/internal/ent/message"
	"github.com/maguowei/gotobeta/internal/ent/messagechange"
	"github.com/maguowei/gotobeta/internal/ent/oauthloginstate"
	"github.com/maguowei/gotobeta/internal/ent/predicate"
	"github.com/maguowei/gotobeta/internal/ent/rbacaclentry"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermission"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermissionchangelog"
	"github.com/maguowei/gotobeta/internal/ent/rbacpermissionversion"
	"github.com/maguowei/gotobeta/internal/ent/rbacrole"
	"github.com/maguowei/gotobeta/internal/ent/rbacrolepermission"
	"github.com/maguowei/gotobeta/internal/ent/rbacuserrole"
	"github.com/maguowei/gotobeta/internal/ent/reaction"
	"github.com/maguowei/gotobeta/internal/ent/todo"
	"github.com/maguowei/gotobeta/internal/ent/user"
	"github.com/maguowei/gotobeta/internal/ent/useridentity"
	"github.com/maguowei/gotobeta/internal/ent/workspace"
	"github.com/maguowei/gotobeta/internal/ent/workspacemember"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The AppSettingFunc type is an adapter to allow the use of ordinary function as a Querier.
type AppSettingFunc func(context.Context, *ent.AppSettingQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AppSettingFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AppSettingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AppSettingQuery", q)
}

// The TraverseAppSetting type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAppSetting func(context.Context, *ent.AppSettingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAppSetting) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAppSetting) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AppSettingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AppSettingQuery", q)
}

// The AttachmentFunc type is an adapter to allow the use of ordinary function as a Querier.
type AttachmentFunc func(context.Context, *ent.AttachmentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AttachmentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AttachmentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AttachmentQuery", q)
}

// The TraverseAttachment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAttachment func(context.Context, *ent.AttachmentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAttachment) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAttachment) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AttachmentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AttachmentQuery", q)
}

// The AuthActionTokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthActionTokenFunc func(context.Context, *ent.AuthActionTokenQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthActionTokenFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthActionTokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthActionTokenQuery", q)
}

// The TraverseAuthActionToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthActionToken func(context.Context, *ent.AuthActionTokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthActionToken) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthActionToken) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthActionTokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthActionTokenQuery", q)
}

// The AuthRefreshTokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthRefreshTokenFunc func(context.Context, *ent.AuthRefreshTokenQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthRefreshTokenFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthRefreshTokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthRefreshTokenQuery", q)
}

// The TraverseAuthRefreshToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthRefreshToken func(context.Context, *ent.AuthRefreshTokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthRefreshToken) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthRefreshToken) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthRefreshTokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthRefreshTokenQuery", q)
}

// The BotFunc type is an adapter to allow the use of ordinary function as a Querier.
type BotFunc func(context.Context, *ent.BotQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f BotFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.BotQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.BotQuery", q)
}

// The TraverseBot type is an adapter to allow the use of ordinary function as Traverser.
type TraverseBot func(context.Context, *ent.BotQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseBot) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseBot) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.BotQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.BotQuery", q)
}

// The ConversationFunc type is an adapter to allow the use of ordinary function as a Querier.
type ConversationFunc func(context.Context, *ent.ConversationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ConversationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ConversationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ConversationQuery", q)
}

// The TraverseConversation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseConversation func(context.Context, *ent.ConversationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseConversation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseConversation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ConversationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ConversationQuery", q)
}

// The ConversationMemberFunc type is an adapter to allow the use of ordinary function as a Querier.
type ConversationMemberFunc func(context.Context, *ent.ConversationMemberQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ConversationMemberFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ConversationMemberQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ConversationMemberQuery", q)
}

// The TraverseConversationMember type is an adapter to allow the use of ordinary function as Traverser.
type TraverseConversationMember func(context.Context, *ent.ConversationMemberQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseConversationMember) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseConversationMember) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ConversationMemberQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ConversationMemberQuery", q)
}

// The MessageFunc type is an adapter to allow the use of ordinary function as a Querier.
type MessageFunc func(context.Context, *ent.MessageQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f MessageFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.MessageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MessageQuery", q)
}

// The TraverseMessage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMessage func(context.Context, *ent.MessageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMessage) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMessage) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MessageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MessageQuery", q)
}

// The MessageChangeFunc type is an adapter to allow the use of ordinary function as a Querier.
type MessageChangeFunc func(context.Context, *ent.MessageChangeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f MessageChangeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.MessageChangeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MessageChangeQuery", q)
}

// The TraverseMessageChange type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMessageChange func(context.Context, *ent.MessageChangeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMessageChange) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMessageChange) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MessageChangeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MessageChangeQuery", q)
}

// The OAuthLoginStateFunc type is an adapter to allow the use of ordinary function as a Querier.
type OAuthLoginStateFunc func(context.Context, *ent.OAuthLoginStateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OAuthLoginStateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OAuthLoginStateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OAuthLoginStateQuery", q)
}

// The TraverseOAuthLoginState type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOAuthLoginState func(context.Context, *ent.OAuthLoginStateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOAuthLoginState) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOAuthLoginState) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OAuthLoginStateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OAuthLoginStateQuery", q)
}

// The RbacAclEntryFunc type is an adapter to allow the use of ordinary function as a Querier.
type RbacAclEntryFunc func(context.Context, *ent.RbacAclEntryQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RbacAclEntryFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RbacAclEntryQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RbacAclEntryQuery", q)
}

// The TraverseRbacAclEntry type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRbacAclEntry func(context.Context, *ent.RbacAclEntryQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRbacAclEntry) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRbacAclEntry) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RbacAclEntryQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RbacAclEntryQuery", q)
}

// The RbacPermissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type RbacPermissionFunc func(context.Context, *ent.RbacPermissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RbacPermissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RbacPermissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RbacPermissionQuery", q)
}

// The TraverseRbacPermission type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRbacPermission func(context.Context, *ent.RbacPermissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRbacPermission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRbacPermission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RbacPermissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RbacPermissionQuery", q)
}

// The RbacPermissionChangeLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type RbacPermissionChangeLogFunc func(context.Context, *ent.RbacPermissionChangeLogQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RbacPermissionChangeLogFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RbacPermissionChangeLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RbacPermissionChangeLogQuery", q)
}

// The TraverseRbacPermissionChangeLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRbacPermissionChangeLog func(context.Context, *ent.RbacPermissionChangeLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRbacPermissionChangeLog) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRbacPermissionChangeLog) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RbacPermissionChangeLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RbacPermissionChangeLogQuery", q)
}

// The RbacPermissionVersionFunc type is an adapter to allow the use of ordinary function as a Querier.
type RbacPermissionVersionFunc func(context.Context, *ent.RbacPermissionVersionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RbacPermissionVersionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RbacPermissionVersionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RbacPermissionVersionQuery", q)
}

// The TraverseRbacPermissionVersion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRbacPermissionVersion func(context.Context, *ent.RbacPermissionVersionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRbacPermissionVersion) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRbacPermissionVersion) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RbacPermissionVersionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RbacPermissionVersionQuery", q)
}

// The RbacRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type RbacRoleFunc func(context.Context, *ent.RbacRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RbacRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RbacRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RbacRoleQuery", q)
}

// The TraverseRbacRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRbacRole func(context.Context, *ent.RbacRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRbacRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRbacRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RbacRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RbacRoleQuery", q)
}

// The RbacRolePermissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type RbacRolePermissionFunc func(context.Context, *ent.RbacRolePermissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RbacRolePermissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RbacRolePermissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RbacRolePermissionQuery", q)
}

// The TraverseRbacRolePermission type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRbacRolePermission func(context.Context, *ent.RbacRolePermissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRbacRolePermission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRbacRolePermission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RbacRolePermissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RbacRolePermissionQuery", q)
}

// The RbacUserRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type RbacUserRoleFunc func(context.Context, *ent.RbacUserRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RbacUserRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RbacUserRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RbacUserRoleQuery", q)
}

// The TraverseRbacUserRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRbacUserRole func(context.Context, *ent.RbacUserRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRbacUserRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRbacUserRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RbacUserRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RbacUserRoleQuery", q)
}

// The ReactionFunc type is an adapter to allow the use of ordinary function as a Querier.
type ReactionFunc func(context.Context, *ent.ReactionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ReactionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ReactionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ReactionQuery", q)
}

// The TraverseReaction type is an adapter to allow the use of ordinary function as Traverser.
type TraverseReaction func(context.Context, *ent.ReactionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseReaction) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseReaction) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ReactionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ReactionQuery", q)
}

// The TodoFunc type is an adapter to allow the use of ordinary function as a Querier.
type TodoFunc func(context.Context, *ent.TodoQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f TodoFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.TodoQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.TodoQuery", q)
}

// The TraverseTodo type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTodo func(context.Context, *ent.TodoQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTodo) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTodo) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TodoQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.TodoQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The UserIdentityFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserIdentityFunc func(context.Context, *ent.UserIdentityQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserIdentityFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserIdentityQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserIdentityQuery", q)
}

// The TraverseUserIdentity type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserIdentity func(context.Context, *ent.UserIdentityQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserIdentity) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserIdentity) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserIdentityQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserIdentityQuery", q)
}

// The WorkspaceFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkspaceFunc func(context.Context, *ent.WorkspaceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkspaceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkspaceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkspaceQuery", q)
}

// The TraverseWorkspace type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkspace func(context.Context, *ent.WorkspaceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkspace) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkspace) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkspaceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkspaceQuery", q)
}

// The WorkspaceMemberFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkspaceMemberFunc func(context.Context, *ent.WorkspaceMemberQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkspaceMemberFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkspaceMemberQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkspaceMemberQuery", q)
}

// The TraverseWorkspaceMember type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkspaceMember func(context.Context, *ent.WorkspaceMemberQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkspaceMember) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkspaceMember) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkspaceMemberQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkspaceMemberQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.AppSettingQuery:
		return &query[*ent.AppSettingQuery, predicate.AppSetting, appsetting.OrderOption]{typ: ent.TypeAppSetting, tq: q}, nil
	case *ent.AttachmentQuery:
		return &query[*ent.AttachmentQuery, predicate.Attachment, attachment.OrderOption]{typ: ent.TypeAttachment, tq: q}, nil
	case *ent.AuthActionTokenQuery:
		return &query[*ent.AuthActionTokenQuery, predicate.AuthActionToken, authactiontoken.OrderOption]{typ: ent.TypeAuthActionToken, tq: q}, nil
	case *ent.AuthRefreshTokenQuery:
		return &query[*ent.AuthRefreshTokenQuery, predicate.AuthRefreshToken, authrefreshtoken.OrderOption]{typ: ent.TypeAuthRefreshToken, tq: q}, nil
	case *ent.BotQuery:
		return &query[*ent.BotQuery, predicate.Bot, bot.OrderOption]{typ: ent.TypeBot, tq: q}, nil
	case *ent.ConversationQuery:
		return &query[*ent.ConversationQuery, predicate.Conversation, conversation.OrderOption]{typ: ent.TypeConversation, tq: q}, nil
	case *ent.ConversationMemberQuery:
		return &query[*ent.ConversationMemberQuery, predicate.ConversationMember, conversationmember.OrderOption]{typ: ent.TypeConversationMember, tq: q}, nil
	case *ent.MessageQuery:
		return &query[*ent.MessageQuery, predicate.Message, message.OrderOption]{typ: ent.TypeMessage, tq: q}, nil
	case *ent.MessageChangeQuery:
		return &query[*ent.MessageChangeQuery, predicate.MessageChange, messagechange.OrderOption]{typ: ent.TypeMessageChange, tq: q}, nil
	case *ent.OAuthLoginStateQuery:
		return &query[*ent.OAuthLoginStateQuery, predicate.OAuthLoginState, oauthloginstate.OrderOption]{typ: ent.TypeOAuthLoginState, tq: q}, nil
	case *ent.RbacAclEntryQuery:
		return &query[*ent.RbacAclEntryQuery, predicate.RbacAclEntry, rbacaclentry.OrderOption]{typ: ent.TypeRbacAclEntry, tq: q}, nil
	case *ent.RbacPermissionQuery:
		return &query[*ent.RbacPermissionQuery, predicate.RbacPermission, rbacpermission.OrderOption]{typ: ent.TypeRbacPermission, tq: q}, nil
	case *ent.RbacPermissionChangeLogQuery:
		return &query[*ent.RbacPermissionChangeLogQuery, predicate.RbacPermissionChangeLog, rbacpermissionchangelog.OrderOption]{typ: ent.TypeRbacPermissionChangeLog, tq: q}, nil
	case *ent.RbacPermissionVersionQuery:
		return &query[*ent.RbacPermissionVersionQuery, predicate.RbacPermissionVersion, rbacpermissionversion.OrderOption]{typ: ent.TypeRbacPermissionVersion, tq: q}, nil
	case *ent.RbacRoleQuery:
		return &query[*ent.RbacRoleQuery, predicate.RbacRole, rbacrole.OrderOption]{typ: ent.TypeRbacRole, tq: q}, nil
	case *ent.RbacRolePermissionQuery:
		return &query[*ent.RbacRolePermissionQuery, predicate.RbacRolePermission, rbacrolepermission.OrderOption]{typ: ent.TypeRbacRolePermission, tq: q}, nil
	case *ent.RbacUserRoleQuery:
		return &query[*ent.RbacUserRoleQuery, predicate.RbacUserRole, rbacuserrole.OrderOption]{typ: ent.TypeRbacUserRole, tq: q}, nil
	case *ent.ReactionQuery:
		return &query[*ent.ReactionQuery, predicate.Reaction, reaction.OrderOption]{typ: ent.TypeReaction, tq: q}, nil
	case *ent.TodoQuery:
		return &query[*ent.TodoQuery, predicate.Todo, todo.OrderOption]{typ: ent.TypeTodo, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	case *ent.UserIdentityQuery:
		return &query[*ent.UserIdentityQuery, predicate.UserIdentity, useridentity.OrderOption]{typ: ent.TypeUserIdentity, tq: q}, nil
	case *ent.WorkspaceQuery:
		return &query[*ent.WorkspaceQuery, predicate.Workspace, workspace.OrderOption]{typ: ent.TypeWorkspace, tq: q}, nil
	case *ent.WorkspaceMemberQuery:
		return &query[*ent.WorkspaceMemberQuery, predicate.WorkspaceMember, workspacemember.OrderOption]{typ: ent.TypeWorkspaceMember, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
